/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 17:03:42 GMT 2017
 */

package com.pearson.eidetic.utilities;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.utilities.HierarchicalIniConfigurationWrapper;
import java.io.File;
import java.io.InputStream;
import org.apache.commons.configuration.HierarchicalINIConfiguration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HierarchicalIniConfigurationWrapper_ESTest extends HierarchicalIniConfigurationWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper("/");
      assertNull(hierarchicalIniConfigurationWrapper0.getConfigurationFilename());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((File) null);
      boolean boolean0 = hierarchicalIniConfigurationWrapper0.isValid();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = HierarchicalIniConfigurationWrapper.saveHierarchicalIniConfigurationToString((HierarchicalINIConfiguration) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper("gpWg5._l&TOE)?!l2");
      hierarchicalIniConfigurationWrapper0.saveHierarchicalIniConfigurationFile((String) null, "gpWg5._l&TOE)?!l2");
      assertNull(hierarchicalIniConfigurationWrapper0.getConfigurationFilename());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HierarchicalIniConfigurationWrapper.saveHierarchicalIniConfigurationFile((File) null, (HierarchicalINIConfiguration) null);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((InputStream) null);
      assertNull(hierarchicalIniConfigurationWrapper0.getConfigurationDirectory());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((String) null);
      String string0 = hierarchicalIniConfigurationWrapper0.saveHierarchicalIniConfigurationToString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((String) null);
      InputStream inputStream0 = hierarchicalIniConfigurationWrapper0.getConfigurationInputStream();
      assertNull(inputStream0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HierarchicalIniConfigurationWrapper.saveHierarchicalIniConfigurationFile("", (String) null, (HierarchicalINIConfiguration) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((String) null);
      hierarchicalIniConfigurationWrapper0.saveHierarchicalIniConfigurationFile((File) null);
      assertNull(hierarchicalIniConfigurationWrapper0.getConfigurationDirectory());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((String) null);
      HierarchicalINIConfiguration hierarchicalINIConfiguration0 = hierarchicalIniConfigurationWrapper0.getHierarchicalIniConfiguration();
      assertNull(hierarchicalINIConfiguration0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((String) null);
      String string0 = hierarchicalIniConfigurationWrapper0.getConfigurationFilename();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((String) null);
      String string0 = hierarchicalIniConfigurationWrapper0.getConfigurationDirectory();
      assertNull(string0);
  }
}
