/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 04 21:27:36 GMT 2016
 */

package com.pearson.eidetic.utilities;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.utilities.HierarchicalIniConfigurationWrapper;
import java.io.File;
import java.io.InputStream;
import org.apache.commons.configuration.HierarchicalINIConfiguration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class HierarchicalIniConfigurationWrapper_ESTest extends HierarchicalIniConfigurationWrapper_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      MockFile mockFile0 = new MockFile("org.eclipse.jetty.http.PathMap", "org.eclipse.jetty.http.PathMap");
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((File) mockFile0);
      HierarchicalINIConfiguration hierarchicalINIConfiguration0 = hierarchicalIniConfigurationWrapper0.getHierarchicalIniConfiguration();
      assertNull(hierarchicalINIConfiguration0);
  }

  @Test
  public void test1()  throws Throwable  {
      String string0 = HierarchicalIniConfigurationWrapper.saveHierarchicalIniConfigurationToString((HierarchicalINIConfiguration) null);
      assertNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      HierarchicalIniConfigurationWrapper.saveHierarchicalIniConfigurationFile("org.eclipse.jetty.http.PathMap", "org.eclipse.jetty.http.PathMap", (HierarchicalINIConfiguration) null);
  }

  @Test
  public void test3()  throws Throwable  {
      MockFile mockFile0 = new MockFile("A2+SJ{T", "A2+SJ{T");
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper("");
      hierarchicalIniConfigurationWrapper0.saveHierarchicalIniConfigurationFile((File) mockFile0);
      assertTrue(mockFile0.isFile());
  }

  @Test
  public void test4()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((InputStream) null);
      assertNull(hierarchicalIniConfigurationWrapper0.getConfigurationDirectory());
  }

  @Test
  public void test5()  throws Throwable  {
      MockFile mockFile0 = new MockFile("org.eclipse.jetty.http.PathMap", "org.eclipse.jetty.http.PathMap");
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((File) mockFile0);
      InputStream inputStream0 = hierarchicalIniConfigurationWrapper0.getConfigurationInputStream();
      assertNull(inputStream0);
  }

  @Test
  public void test6()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper("");
      hierarchicalIniConfigurationWrapper0.saveHierarchicalIniConfigurationFile("", "^:\"anm-/9M5");
      assertNull(hierarchicalIniConfigurationWrapper0.getConfigurationFilename());
  }

  @Test
  public void test7()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((File) null);
      String string0 = hierarchicalIniConfigurationWrapper0.saveHierarchicalIniConfigurationToString();
      assertNull(string0);
  }

  @Test
  public void test8()  throws Throwable  {
      HierarchicalIniConfigurationWrapper hierarchicalIniConfigurationWrapper0 = new HierarchicalIniConfigurationWrapper((String) null);
      String string0 = hierarchicalIniConfigurationWrapper0.getConfigurationDirectory();
      assertNull(string0);
  }
}
