/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 17:05:28 GMT 2017
 */

package com.pearson.eidetic.utilities;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.utilities.StackTrace;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StackTrace_ESTest extends StackTrace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = StackTrace.getStringFromStackTrace((StackTraceElement[]) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[24];
      String string0 = StackTrace.getStringFromStackTrace(stackTraceElementArray0);
      assertEquals("null\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\nnull\n", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[0];
      String string0 = StackTrace.getStringFromStackTrace(stackTraceElementArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = StackTrace.getStringFromStackTrace((Exception) null);
      assertEquals("<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StackTrace stackTrace0 = new StackTrace();
  }
}
