/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 13 18:03:00 GMT 2015
 */

package com.pearson.eidetic.utilities;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.utilities.StackTrace;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class StackTrace_ESTest extends StackTrace_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      StackTrace stackTrace0 = new StackTrace();
  }

  @Test
  public void test1()  throws Throwable  {
      String string0 = StackTrace.getStringFromStackTrace((Exception) null);
      assertEquals("<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n<evosuite>.<evosuite>(<evosuite>)\n", string0);
  }
}
