/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 17:01:41 GMT 2017
 */

package com.pearson.eidetic.driver.threads;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.pearson.eidetic.aws.AwsAccount;
import com.pearson.eidetic.driver.threads.MonitorVolumeSyncValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MonitorVolumeSyncValidator_ESTest extends MonitorVolumeSyncValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MonitorVolumeSyncValidator monitorVolumeSyncValidator0 = null;
      try {
        monitorVolumeSyncValidator0 = new MonitorVolumeSyncValidator((AwsAccount) null, (Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.MonitorVolumeSyncValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = Integer.valueOf((-98));
      MonitorVolumeSyncValidator monitorVolumeSyncValidator0 = new MonitorVolumeSyncValidator((AwsAccount) null, integer0);
  }
}
