/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 04 21:35:25 GMT 2016
 */

package com.pearson.eidetic.driver.threads;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.pearson.eidetic.aws.AwsAccount;
import com.pearson.eidetic.driver.threads.MonitorSnapshotCleaner;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MonitorSnapshotCleaner_ESTest extends MonitorSnapshotCleaner_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      MonitorSnapshotCleaner monitorSnapshotCleaner0 = new MonitorSnapshotCleaner((AwsAccount) null);
      // Undeclared exception!
      try { 
        monitorSnapshotCleaner0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.pearson.eidetic.driver.threads.MonitorSnapshotCleaner", e);
      }
  }
}
