/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 16:58:41 GMT 2017
 */

package com.pearson.eidetic.driver.threads;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.pearson.eidetic.aws.AwsAccount;
import com.pearson.eidetic.driver.threads.RefreshAwsAccountVolumes;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RefreshAwsAccountVolumes_ESTest extends RefreshAwsAccountVolumes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RefreshAwsAccountVolumes refreshAwsAccountVolumes0 = null;
      try {
        refreshAwsAccountVolumes0 = new RefreshAwsAccountVolumes((AwsAccount) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.RefreshAwsAccountVolumes", e);
      }
  }
}
