/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 16:57:15 GMT 2017
 */

package com.pearson.eidetic.aws;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.pearson.eidetic.aws.AwsAccount;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AwsAccount_ESTest extends AwsAccount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Boolean boolean0 = new Boolean(true);
      AwsAccount awsAccount0 = null;
      try {
        awsAccount0 = new AwsAccount(0, "KS_cC?9?wI{w2", (String) null, "CreateAfter", integer0, boolean0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Access key cannot be null.
         //
         verifyException("com.amazonaws.auth.BasicAWSCredentials", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AwsAccount awsAccount0 = null;
      try {
        awsAccount0 = new AwsAccount((-2474), "W^b!k", "W^b!k", "W^b!k", (Integer) null, (Boolean) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class com.amazonaws.ClientConfiguration
         //
         verifyException("com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient", e);
      }
  }
}
