/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 28 16:57:15 GMT 2017
 */

package com.pearson.eidetic.aws;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class AwsAccount_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.pearson.eidetic.aws.AwsAccount"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("os.name", "Mac OS X"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/Users/testuser"); 
    java.lang.System.setProperty("java.home", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre"); 
    java.lang.System.setProperty("user.dir", "/Users/testuser/Documents/NetBeansProjects/eidetic"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
    java.lang.System.setProperty("awt.toolkit", "sun.lwawt.macosx.LWCToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
    java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.CGraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.lwawt.macosx.CPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/EvoSuite_pathingJar7870507141901064177.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
    java.lang.System.setProperty("java.endorsed.dirs", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/Users/testuser/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_25-b17"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_25"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.version", "25.25-b02"); 
    java.lang.System.setProperty("os.arch", "x86_64"); 
    java.lang.System.setProperty("os.version", "10.10.5"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "testuser"); 
    java.lang.System.setProperty("user.timezone", "America/Chicago"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AwsAccount_ESTest_scaffolding.class.getClassLoader() ,
      "com.amazonaws.services.identitymanagement.model.ListSigningCertificatesRequest",
      "com.amazonaws.services.identitymanagement.model.CreatePolicyRequest",
      "com.amazonaws.services.identitymanagement.model.DeleteGroupRequest",
      "com.fasterxml.jackson.databind.deser.BeanDeserializerModifier",
      "com.amazonaws.event.ProgressListener$1",
      "com.fasterxml.jackson.databind.deser.impl.FieldProperty",
      "com.amazonaws.services.identitymanagement.model.DeleteAccountAliasRequest",
      "com.fasterxml.jackson.databind.deser.std.EnumDeserializer",
      "com.fasterxml.jackson.annotation.ObjectIdGenerators$Base",
      "com.fasterxml.jackson.databind.introspect.AnnotatedConstructor",
      "com.amazonaws.services.identitymanagement.model.UpdateServerCertificateRequest",
      "com.amazonaws.services.ec2.model.DescribeInstancesRequest",
      "com.fasterxml.jackson.databind.cfg.MapperConfigBase",
      "com.fasterxml.jackson.databind.deser.UnresolvedForwardReference",
      "com.amazonaws.services.identitymanagement.model.AttachUserPolicyRequest",
      "com.fasterxml.jackson.databind.ser.impl.UnknownSerializer",
      "com.amazonaws.services.rds.model.AddTagsToResourceRequest",
      "com.fasterxml.jackson.databind.deser.std.StdKeyDeserializers",
      "com.amazonaws.services.identitymanagement.AmazonIdentityManagement",
      "com.amazonaws.auth.AWSCredentials",
      "com.fasterxml.jackson.databind.type.MapLikeType",
      "com.fasterxml.jackson.databind.type.MapType",
      "com.amazonaws.services.identitymanagement.model.ResyncMFADeviceRequest",
      "com.amazonaws.handlers.RequestHandler2",
      "com.amazonaws.metrics.RequestMetricCollector$1",
      "com.amazonaws.internal.config.SignerConfig",
      "com.fasterxml.jackson.databind.ObjectWriter",
      "com.fasterxml.jackson.databind.deser.std.FromStringDeserializer",
      "com.fasterxml.jackson.databind.type.TypeBase",
      "com.fasterxml.jackson.databind.deser.impl.ManagedReferenceProperty",
      "com.fasterxml.jackson.databind.ser.std.DateTimeSerializerBase",
      "com.amazonaws.AmazonClientException",
      "com.amazonaws.services.identitymanagement.model.ListInstanceProfilesRequest",
      "com.amazonaws.services.identitymanagement.model.UploadSigningCertificateRequest",
      "com.amazonaws.services.identitymanagement.model.DeleteUserPolicyRequest",
      "com.amazonaws.services.rds.model.DescribeDBSnapshotsRequest",
      "com.amazonaws.transform.Unmarshaller",
      "com.fasterxml.jackson.databind.deser.Deserializers",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "com.fasterxml.jackson.databind.util.Annotations",
      "com.fasterxml.jackson.databind.deser.KeyDeserializers",
      "com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitable",
      "com.amazonaws.services.identitymanagement.model.CreateOpenIDConnectProviderRequest",
      "com.fasterxml.jackson.databind.type.CollectionLikeType",
      "com.fasterxml.jackson.core.TreeNode",
      "com.fasterxml.jackson.databind.node.NumericNode",
      "com.fasterxml.jackson.databind.deser.ValueInstantiator",
      "com.amazonaws.services.identitymanagement.model.GetRolePolicyRequest",
      "com.amazonaws.services.rds.model.DeleteDBSnapshotRequest",
      "com.amazonaws.services.identitymanagement.model.CreateGroupRequest",
      "com.amazonaws.log.CommonsLogFactory",
      "com.fasterxml.jackson.core.base.ParserMinimalBase",
      "com.fasterxml.jackson.databind.deser.std.MapEntryDeserializer",
      "com.amazonaws.services.ec2.model.DescribeSnapshotsResult",
      "com.fasterxml.jackson.databind.deser.BeanDeserializerBase",
      "com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition",
      "com.amazonaws.services.identitymanagement.model.DeleteSSHPublicKeyRequest",
      "com.amazonaws.services.identitymanagement.model.UploadServerCertificateRequest",
      "com.fasterxml.jackson.core.SerializableString",
      "com.fasterxml.jackson.databind.deser.ValueInstantiators",
      "com.fasterxml.jackson.core.Versioned",
      "com.fasterxml.jackson.databind.introspect.VirtualAnnotatedMember",
      "com.amazonaws.util.IOUtils",
      "com.amazonaws.services.identitymanagement.model.UpdateAccountPasswordPolicyRequest",
      "com.amazonaws.metrics.MetricType",
      "com.fasterxml.jackson.databind.deser.std.EnumSetDeserializer",
      "com.fasterxml.jackson.databind.JsonSerializable",
      "com.fasterxml.jackson.databind.introspect.AnnotatedMember",
      "com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer",
      "com.amazonaws.services.identitymanagement.model.DeleteSigningCertificateRequest",
      "com.amazonaws.services.rds.model.DescribeDBSnapshotsResult",
      "com.amazonaws.services.identitymanagement.model.UpdateUserRequest",
      "com.amazonaws.services.identitymanagement.model.GetLoginProfileRequest",
      "com.fasterxml.jackson.databind.introspect.AnnotatedWithParams",
      "com.amazonaws.services.identitymanagement.model.GetUserRequest",
      "com.amazonaws.services.identitymanagement.model.DetachUserPolicyRequest",
      "com.fasterxml.jackson.databind.exc.IgnoredPropertyException",
      "com.amazonaws.services.identitymanagement.model.CreateLoginProfileRequest",
      "com.amazonaws.services.identitymanagement.model.GetSAMLProviderRequest",
      "com.amazonaws.services.identitymanagement.model.GetGroupPolicyRequest",
      "com.amazonaws.services.identitymanagement.model.GetPolicyRequest",
      "com.fasterxml.jackson.databind.ser.SerializerFactory",
      "com.amazonaws.services.identitymanagement.model.ListAccountAliasesRequest",
      "com.fasterxml.jackson.databind.type.SimpleType",
      "com.fasterxml.jackson.databind.ser.ContextualSerializer",
      "com.fasterxml.jackson.databind.DeserializationConfig",
      "com.fasterxml.jackson.databind.node.ContainerNode",
      "com.fasterxml.jackson.databind.deser.BeanDeserializerFactory",
      "com.fasterxml.jackson.databind.ser.std.StdSerializer",
      "com.amazonaws.services.identitymanagement.model.GetAccessKeyLastUsedRequest",
      "com.fasterxml.jackson.databind.ser.BeanSerializerFactory",
      "com.fasterxml.jackson.databind.jsonschema.SchemaAware",
      "com.amazonaws.log.InternalLogFactory",
      "com.fasterxml.jackson.databind.AbstractTypeResolver",
      "com.amazonaws.services.identitymanagement.model.ListPolicyVersionsRequest",
      "com.amazonaws.services.identitymanagement.model.DeletePolicyVersionRequest",
      "com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer",
      "com.fasterxml.jackson.databind.deser.std.ArrayBlockingQueueDeserializer",
      "com.amazonaws.services.identitymanagement.model.DetachRolePolicyRequest",
      "com.amazonaws.RequestClientOptions$Marker",
      "com.fasterxml.jackson.core.PrettyPrinter",
      "com.amazonaws.services.identitymanagement.model.DeactivateMFADeviceRequest",
      "com.pearson.eidetic.globals.GlobalVariables",
      "com.amazonaws.ReadLimitInfo",
      "com.amazonaws.services.identitymanagement.model.ListServerCertificatesRequest",
      "com.amazonaws.services.identitymanagement.model.ListInstanceProfilesForRoleRequest",
      "com.fasterxml.jackson.core.base.GeneratorBase",
      "com.fasterxml.jackson.databind.exc.PropertyBindingException",
      "com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector",
      "com.amazonaws.services.rds.model.CreateDBSnapshotRequest",
      "com.amazonaws.services.identitymanagement.model.ListUsersRequest",
      "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
      "com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder",
      "com.amazonaws.services.identitymanagement.model.GenerateCredentialReportRequest",
      "com.amazonaws.services.identitymanagement.model.AttachGroupPolicyRequest",
      "com.fasterxml.jackson.databind.introspect.NopAnnotationIntrospector",
      "com.fasterxml.jackson.core.json.JsonWriteContext",
      "com.fasterxml.jackson.annotation.ObjectIdGenerators$PropertyGenerator",
      "com.fasterxml.jackson.core.io.UTF8Writer",
      "com.fasterxml.jackson.databind.BeanProperty",
      "com.pearson.eidetic.aws.RDSClientMethods",
      "com.pearson.eidetic.aws.EC2ClientMethods",
      "com.amazonaws.services.identitymanagement.model.ListAttachedUserPoliciesRequest",
      "com.amazonaws.services.identitymanagement.model.CreateAccessKeyRequest",
      "com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer",
      "com.amazonaws.services.ec2.model.DeleteSnapshotRequest",
      "com.fasterxml.jackson.core.base.ParserBase",
      "com.fasterxml.jackson.core.JsonGenerator",
      "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext",
      "com.amazonaws.SignableRequest",
      "com.amazonaws.services.rds.AmazonRDS",
      "com.amazonaws.services.identitymanagement.model.GetAccountPasswordPolicyRequest",
      "com.amazonaws.services.identitymanagement.model.CreatePolicyVersionRequest",
      "com.amazonaws.http.ExecutionContext",
      "com.fasterxml.jackson.core.JsonGenerationException",
      "com.amazonaws.services.rds.model.DBSnapshot",
      "com.amazonaws.Protocol",
      "com.fasterxml.jackson.databind.ser.std.JsonValueSerializer",
      "com.fasterxml.jackson.core.TreeCodec",
      "com.fasterxml.jackson.databind.deser.impl.SetterlessProperty",
      "com.amazonaws.services.identitymanagement.model.GetServerCertificateRequest",
      "com.fasterxml.jackson.core.json.UTF8JsonGenerator",
      "com.amazonaws.services.identitymanagement.model.ListSSHPublicKeysRequest",
      "com.amazonaws.services.rds.model.DeleteDBClusterSnapshotRequest",
      "com.amazonaws.services.identitymanagement.model.UploadSSHPublicKeyRequest",
      "com.amazonaws.services.rds.model.ListTagsForResourceRequest",
      "com.amazonaws.log.JulLogFactory",
      "com.fasterxml.jackson.databind.ser.std.SerializableSerializer",
      "com.fasterxml.jackson.databind.introspect.Annotated",
      "com.amazonaws.services.identitymanagement.model.GetCredentialReportRequest",
      "com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer$DelegatingKD",
      "com.amazonaws.services.ec2.model.CreateSnapshotRequest",
      "com.amazonaws.services.rds.model.DescribeDBInstancesRequest",
      "com.amazonaws.services.identitymanagement.model.DeleteInstanceProfileRequest",
      "com.fasterxml.jackson.core.json.WriterBasedJsonGenerator",
      "com.amazonaws.services.identitymanagement.model.DeleteUserRequest",
      "com.fasterxml.jackson.databind.deser.CreatorProperty",
      "com.amazonaws.services.identitymanagement.model.CreateVirtualMFADeviceRequest",
      "com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer$StringCtorKeyDeserializer",
      "com.amazonaws.services.identitymanagement.model.AddRoleToInstanceProfileRequest",
      "com.fasterxml.jackson.databind.annotation.JacksonStdImpl",
      "com.fasterxml.jackson.core.JsonParseException",
      "com.amazonaws.services.ec2.model.CopySnapshotResult",
      "com.amazonaws.services.identitymanagement.model.CreateRoleRequest",
      "com.amazonaws.services.identitymanagement.model.CreateAccountAliasRequest",
      "com.amazonaws.services.ec2.model.DescribeVolumesResult",
      "com.amazonaws.services.ec2.model.DescribeInstancesResult",
      "com.amazonaws.services.identitymanagement.model.DeleteAccountPasswordPolicyRequest",
      "com.fasterxml.jackson.databind.introspect.AnnotatedClass",
      "com.fasterxml.jackson.databind.deser.std.AtomicReferenceDeserializer",
      "com.fasterxml.jackson.databind.ser.impl.FailingSerializer",
      "com.amazonaws.services.identitymanagement.model.AttachRolePolicyRequest",
      "com.fasterxml.jackson.databind.JsonMappingException",
      "com.amazonaws.services.identitymanagement.model.ListRolePoliciesRequest",
      "com.fasterxml.jackson.databind.deser.std.StdScalarDeserializer",
      "com.amazonaws.Request",
      "com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer",
      "com.amazonaws.services.identitymanagement.model.CreateUserRequest",
      "com.amazonaws.services.identitymanagement.model.DeleteGroupPolicyRequest",
      "com.fasterxml.jackson.databind.DatabindContext",
      "com.fasterxml.jackson.databind.node.ObjectNode",
      "com.amazonaws.services.identitymanagement.model.ListAccessKeysRequest",
      "com.amazonaws.services.identitymanagement.model.AddClientIDToOpenIDConnectProviderRequest",
      "com.amazonaws.services.ec2.AmazonEC2",
      "com.amazonaws.services.identitymanagement.model.GetGroupRequest",
      "com.fasterxml.jackson.databind.introspect.AnnotatedField",
      "com.amazonaws.services.identitymanagement.model.RemoveRoleFromInstanceProfileRequest",
      "com.amazonaws.services.identitymanagement.model.GetInstanceProfileRequest",
      "com.amazonaws.AmazonWebServiceRequest$1",
      "com.fasterxml.jackson.databind.deser.std.ContainerDeserializerBase",
      "com.amazonaws.AmazonWebServiceRequest",
      "com.amazonaws.auth.BasicAWSCredentials",
      "com.fasterxml.jackson.databind.deser.ContextualDeserializer",
      "com.fasterxml.jackson.annotation.ObjectIdGenerator",
      "com.fasterxml.jackson.databind.ser.std.CalendarSerializer",
      "com.amazonaws.regions.RegionMetadata",
      "com.amazonaws.services.identitymanagement.model.RemoveUserFromGroupRequest",
      "com.amazonaws.internal.config.InternalConfig",
      "com.amazonaws.ApacheHttpClientConfig",
      "com.amazonaws.services.rds.model.DescribeDBClustersResult",
      "com.amazonaws.AmazonWebServiceClient",
      "com.amazonaws.services.identitymanagement.model.DeleteLoginProfileRequest",
      "com.amazonaws.RequestClientOptions",
      "com.amazonaws.metrics.RequestMetricCollector",
      "com.fasterxml.jackson.databind.deser.std.CollectionDeserializer",
      "com.fasterxml.jackson.databind.node.TreeTraversingParser",
      "com.fasterxml.jackson.databind.deser.std.FromStringDeserializer$Std",
      "com.fasterxml.jackson.databind.type.ArrayType",
      "com.fasterxml.jackson.databind.util.Named",
      "com.amazonaws.regions.RegionUtils",
      "com.amazonaws.services.identitymanagement.model.DeleteOpenIDConnectProviderRequest",
      "com.fasterxml.jackson.databind.type.CollectionType",
      "com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer",
      "com.fasterxml.jackson.databind.ser.std.StdScalarSerializer",
      "com.amazonaws.services.identitymanagement.model.GetPolicyVersionRequest",
      "com.fasterxml.jackson.databind.introspect.NopAnnotationIntrospector$1",
      "com.amazonaws.services.identitymanagement.model.GetAccountSummaryRequest",
      "com.fasterxml.jackson.databind.node.ValueNode",
      "com.amazonaws.services.rds.model.DescribeDBClusterSnapshotsRequest",
      "com.amazonaws.services.rds.model.CreateDBClusterSnapshotRequest",
      "com.amazonaws.Response",
      "com.fasterxml.jackson.databind.ser.BasicSerializerFactory",
      "com.fasterxml.jackson.databind.deser.std.EnumMapDeserializer",
      "com.amazonaws.services.identitymanagement.model.GetRoleRequest",
      "com.fasterxml.jackson.databind.deser.SettableBeanProperty",
      "com.fasterxml.jackson.databind.node.JsonNodeCreator",
      "com.amazonaws.internal.config.Builder",
      "com.fasterxml.jackson.core.json.ReaderBasedJsonParser",
      "com.pearson.eidetic.utilities.Threads",
      "com.fasterxml.jackson.databind.jsontype.SubtypeResolver",
      "com.fasterxml.jackson.core.ObjectCodec",
      "com.fasterxml.jackson.core.json.JsonReadContext",
      "com.amazonaws.regions.Regions",
      "com.amazonaws.services.identitymanagement.model.ListMFADevicesRequest",
      "com.amazonaws.services.identitymanagement.model.ListAttachedRolePoliciesRequest",
      "com.amazonaws.services.rds.model.DescribeDBInstancesResult",
      "com.amazonaws.services.ec2.model.DescribeVolumesRequest",
      "com.amazonaws.services.rds.AmazonRDSClient",
      "com.fasterxml.jackson.databind.KeyDeserializer",
      "com.amazonaws.services.ec2.AmazonEC2Client",
      "com.fasterxml.jackson.databind.deser.impl.PropertyBasedObjectIdGenerator",
      "com.fasterxml.jackson.annotation.ObjectIdResolver",
      "com.fasterxml.jackson.databind.DeserializationContext",
      "com.amazonaws.services.identitymanagement.model.UpdateAssumeRolePolicyRequest",
      "com.amazonaws.util.AWSRequestMetricsFullSupport",
      "com.amazonaws.ClientConfiguration",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.fasterxml.jackson.databind.ser.PropertyWriter",
      "com.fasterxml.jackson.core.util.ByteArrayBuilder",
      "com.pearson.eidetic.aws.AwsAccount",
      "com.amazonaws.services.rds.model.DescribeDBClustersRequest",
      "com.amazonaws.util.ClassLoaderHelper",
      "com.amazonaws.services.rds.model.CopyOptionGroupRequest",
      "com.amazonaws.internal.config.HttpClientConfig",
      "com.amazonaws.retry.RetryPolicy",
      "com.amazonaws.services.identitymanagement.model.UpdateLoginProfileRequest",
      "com.amazonaws.services.identitymanagement.model.DeletePolicyRequest",
      "com.fasterxml.jackson.databind.AnnotationIntrospector",
      "com.fasterxml.jackson.databind.ser.std.DateSerializer",
      "com.fasterxml.jackson.databind.ser.std.NullSerializer",
      "com.fasterxml.jackson.databind.deser.std.StringDeserializer",
      "com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "com.fasterxml.jackson.databind.deser.impl.BeanAsArrayDeserializer",
      "com.amazonaws.services.ec2.model.CreateTagsRequest",
      "com.amazonaws.services.identitymanagement.model.ListUserPoliciesRequest",
      "com.fasterxml.jackson.databind.node.BaseJsonNode",
      "com.fasterxml.jackson.databind.JsonDeserializer",
      "com.fasterxml.jackson.databind.util.SimpleBeanPropertyDefinition",
      "com.fasterxml.jackson.databind.deser.impl.MethodProperty",
      "com.amazonaws.services.identitymanagement.model.DeleteSAMLProviderRequest",
      "com.amazonaws.services.identitymanagement.model.PutRolePolicyRequest",
      "com.amazonaws.services.identitymanagement.model.AddUserToGroupRequest",
      "com.amazonaws.services.identitymanagement.model.CreateInstanceProfileRequest",
      "com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla",
      "com.amazonaws.services.ec2.model.DescribeSnapshotsRequest",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "com.fasterxml.jackson.databind.exc.InvalidFormatException",
      "com.fasterxml.jackson.databind.deser.std.MapDeserializer",
      "com.fasterxml.jackson.databind.deser.std.TokenBufferDeserializer",
      "com.fasterxml.jackson.core.type.ResolvedType",
      "com.amazonaws.services.identitymanagement.model.ListGroupsRequest",
      "com.amazonaws.services.rds.model.ListTagsForResourceResult",
      "com.amazonaws.services.identitymanagement.model.ListVirtualMFADevicesRequest",
      "com.fasterxml.jackson.databind.introspect.AnnotatedMethod",
      "com.amazonaws.services.identitymanagement.model.DetachGroupPolicyRequest",
      "com.amazonaws.services.identitymanagement.model.UpdateGroupRequest",
      "com.fasterxml.jackson.databind.introspect.VisibilityChecker",
      "com.amazonaws.services.identitymanagement.model.GetUserPolicyRequest",
      "com.fasterxml.jackson.databind.introspect.AnnotatedParameter",
      "com.fasterxml.jackson.core.JsonParser",
      "com.amazonaws.services.ec2.model.DryRunSupportedRequest",
      "com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
      "com.fasterxml.jackson.core.JsonProcessingException",
      "com.fasterxml.jackson.core.JsonStreamContext",
      "com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient",
      "com.amazonaws.internal.config.InternalConfig$Factory",
      "com.amazonaws.services.identitymanagement.model.DeleteRoleRequest",
      "com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer",
      "com.amazonaws.services.ec2.model.CopySnapshotRequest",
      "com.amazonaws.services.identitymanagement.model.ListAttachedGroupPoliciesRequest",
      "com.amazonaws.services.identitymanagement.model.UpdateSSHPublicKeyRequest",
      "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl",
      "com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException",
      "com.amazonaws.services.identitymanagement.model.EnableMFADeviceRequest",
      "com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver",
      "com.amazonaws.event.ProgressListener",
      "com.fasterxml.jackson.databind.deser.std.StdDeserializer",
      "com.amazonaws.services.identitymanagement.model.ListPoliciesRequest",
      "com.fasterxml.jackson.databind.JsonSerializer",
      "com.fasterxml.jackson.databind.JsonNode",
      "com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig",
      "com.amazonaws.services.identitymanagement.model.PutUserPolicyRequest",
      "com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty",
      "com.fasterxml.jackson.databind.ser.ResolvableSerializer",
      "com.amazonaws.services.identitymanagement.model.UpdateSigningCertificateRequest",
      "com.amazonaws.services.identitymanagement.model.ListGroupsForUserRequest",
      "com.fasterxml.jackson.databind.PropertyName",
      "com.amazonaws.services.identitymanagement.model.GetSSHPublicKeyRequest",
      "com.amazonaws.services.identitymanagement.model.DeleteServerCertificateRequest",
      "com.amazonaws.services.identitymanagement.model.RemoveClientIDFromOpenIDConnectProviderRequest",
      "com.amazonaws.services.identitymanagement.model.CreateSAMLProviderRequest",
      "com.fasterxml.jackson.databind.deser.BasicDeserializerFactory",
      "com.amazonaws.http.HttpResponseHandler",
      "com.amazonaws.services.identitymanagement.model.DeleteAccessKeyRequest",
      "com.amazonaws.services.identitymanagement.model.DeleteRolePolicyRequest",
      "com.fasterxml.jackson.databind.cfg.MapperConfig",
      "com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer$StringKD",
      "com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer$StringFactoryKeyDeserializer",
      "com.fasterxml.jackson.databind.deser.impl.InnerClassProperty",
      "com.amazonaws.services.identitymanagement.model.GetAccountAuthorizationDetailsRequest",
      "com.amazonaws.services.identitymanagement.model.ListSAMLProvidersRequest",
      "com.fasterxml.jackson.databind.MappingJsonFactory",
      "com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer",
      "com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair",
      "com.amazonaws.util.json.Jackson",
      "com.amazonaws.services.rds.model.DescribeDBClusterSnapshotsResult",
      "com.amazonaws.services.identitymanagement.model.DeleteVirtualMFADeviceRequest",
      "com.amazonaws.auth.AWSCredentialsProvider",
      "com.fasterxml.jackson.databind.JavaType",
      "com.fasterxml.jackson.databind.deser.BeanDeserializer",
      "com.amazonaws.services.identitymanagement.model.ListOpenIDConnectProvidersRequest",
      "com.amazonaws.services.ec2.model.CreateSnapshotResult",
      "com.amazonaws.log.CommonsLog",
      "com.amazonaws.services.identitymanagement.model.UpdateOpenIDConnectProviderThumbprintRequest",
      "com.amazonaws.services.ec2.model.DeleteTagsRequest",
      "com.fasterxml.jackson.core.JsonFactory",
      "com.amazonaws.services.identitymanagement.model.UpdateSAMLProviderRequest",
      "com.fasterxml.jackson.databind.deser.impl.FailingDeserializer",
      "com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer$EnumKD",
      "com.fasterxml.jackson.databind.node.MissingNode",
      "com.amazonaws.services.identitymanagement.model.ListGroupPoliciesRequest",
      "com.fasterxml.jackson.databind.util.StdDateFormat",
      "com.fasterxml.jackson.databind.SerializationConfig",
      "com.fasterxml.jackson.databind.deser.ResolvableDeserializer",
      "com.amazonaws.services.identitymanagement.model.UpdateAccessKeyRequest",
      "com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer",
      "com.amazonaws.handlers.RequestHandler2Adaptor",
      "com.amazonaws.services.ec2.model.DescribeAvailabilityZonesRequest",
      "com.amazonaws.handlers.RequestHandler",
      "com.amazonaws.services.identitymanagement.model.PutGroupPolicyRequest",
      "com.amazonaws.services.identitymanagement.model.ListEntitiesForPolicyRequest",
      "com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer",
      "com.fasterxml.jackson.databind.deser.DeserializerFactory",
      "com.amazonaws.services.identitymanagement.model.GetOpenIDConnectProviderRequest",
      "com.amazonaws.services.identitymanagement.model.SetDefaultPolicyVersionRequest",
      "com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty",
      "com.fasterxml.jackson.databind.introspect.ClassIntrospector$MixInResolver",
      "com.fasterxml.jackson.core.json.JsonGeneratorImpl",
      "com.amazonaws.util.AWSRequestMetrics",
      "com.amazonaws.internal.config.InternalConfigJsonHelper",
      "com.fasterxml.jackson.databind.deser.AbstractDeserializer",
      "com.amazonaws.util.VersionInfoUtils",
      "org.apache.commons.logging.impl.Log4JLogger",
      "com.amazonaws.internal.config.JsonIndex",
      "com.amazonaws.services.identitymanagement.model.ChangePasswordRequest",
      "com.amazonaws.auth.Signer",
      "com.fasterxml.jackson.databind.deser.std.JsonLocationInstantiator",
      "com.amazonaws.services.identitymanagement.model.ListRolesRequest",
      "com.fasterxml.jackson.databind.SerializerProvider",
      "com.amazonaws.services.rds.model.DBClusterSnapshot",
      "com.fasterxml.jackson.databind.deser.std.EnumDeserializer$FactoryBasedDeserializer",
      "com.fasterxml.jackson.databind.ObjectMapper",
      "com.amazonaws.regions.RegionMetadataParser",
      "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl",
      "com.amazonaws.regions.Region",
      "com.amazonaws.log.InternalLogApi"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AwsAccount_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.pearson.eidetic.aws.AwsAccount",
      "com.amazonaws.regions.RegionUtils",
      "com.amazonaws.util.IOUtils",
      "com.amazonaws.regions.Regions",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.amazonaws.Protocol",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "com.pearson.eidetic.utilities.Threads",
      "com.pearson.eidetic.globals.GlobalVariables",
      "com.pearson.eidetic.aws.EC2ClientMethods",
      "com.pearson.eidetic.aws.RDSClientMethods",
      "com.amazonaws.regions.RegionMetadataParser",
      "com.amazonaws.regions.Region",
      "com.amazonaws.log.InternalLogFactory",
      "com.amazonaws.AmazonWebServiceClient",
      "com.amazonaws.util.VersionInfoUtils",
      "com.amazonaws.internal.config.InternalConfig",
      "com.amazonaws.util.ClassLoaderHelper",
      "com.amazonaws.util.json.Jackson",
      "com.amazonaws.internal.config.InternalConfig$Factory",
      "com.amazonaws.ClientConfiguration",
      "org.apache.commons.logging.impl.Jdk14Logger"
    );
  }
}
