/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 17:05:41 GMT 2017
 */

package com.pearson.eidetic.aws;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.aws.CredentialSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CredentialSet_ESTest extends CredentialSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet("LtN)iK*p#V5Gb", (String) null);
      String string0 = credentialSet0.getAWSSecretKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet("O,U~E>o?Z)QEYiI", "");
      String string0 = credentialSet0.getAWSSecretKey();
      assertEquals("", string0);
      assertEquals("O,U~E>o?Z)QEYiI", credentialSet0.getAWSAccessKeyId());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet((String) null, "");
      String string0 = credentialSet0.getAWSAccessKeyId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet("1*Z[7Q\"|#}x}mB {", "1*Z[7Q\"|#}x}mB {");
      String string0 = credentialSet0.getAWSAccessKeyId();
      assertEquals("1*Z[7Q\"|#}x}mB {", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet("", "O,U~E>o?Z)QEYiI");
      String string0 = credentialSet0.getAWSSecretKey();
      assertEquals("", credentialSet0.getAWSAccessKeyId());
      assertEquals("O,U~E>o?Z)QEYiI", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet("", "O,U~E>o?Z)QEYiI");
      String string0 = credentialSet0.getAWSAccessKeyId();
      assertEquals("", string0);
      assertEquals("O,U~E>o?Z)QEYiI", credentialSet0.getAWSSecretKey());
  }
}
