/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 13 18:03:07 GMT 2015
 */

package com.pearson.eidetic.aws;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.aws.CredentialSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CredentialSet_ESTest extends CredentialSet_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet((String) null, "^a!Rw<'Z,I!A");
      String string0 = credentialSet0.getAWSAccessKeyId();
      assertNull(string0);
  }

  @Test
  public void test1()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet("3h*9l*", (String) null);
      String string0 = credentialSet0.getAWSSecretKey();
      assertNull(string0);
  }

  @Test
  public void test2()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet("u6''+NU", "u6''+NU");
      String string0 = credentialSet0.getAWSSecretKey();
      assertEquals("u6''+NU", string0);
  }

  @Test
  public void test3()  throws Throwable  {
      CredentialSet credentialSet0 = new CredentialSet("u6''+NU", "u6''+NU");
      String string0 = credentialSet0.getAWSAccessKeyId();
      assertEquals("u6''+NU", string0);
  }
}
