/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 16:57:57 GMT 2017
 */

package com.pearson.eidetic.aws;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.amazonaws.services.rds.AmazonRDS;
import com.amazonaws.services.rds.AmazonRDSClient;
import com.amazonaws.services.rds.model.AddTagsToResourceRequest;
import com.amazonaws.services.rds.model.CreateDBClusterSnapshotRequest;
import com.amazonaws.services.rds.model.CreateDBSnapshotRequest;
import com.amazonaws.services.rds.model.DBClusterSnapshot;
import com.amazonaws.services.rds.model.DBSnapshot;
import com.amazonaws.services.rds.model.DeleteDBClusterSnapshotRequest;
import com.amazonaws.services.rds.model.DeleteDBSnapshotRequest;
import com.amazonaws.services.rds.model.DescribeDBClusterSnapshotsRequest;
import com.amazonaws.services.rds.model.DescribeDBClusterSnapshotsResult;
import com.amazonaws.services.rds.model.DescribeDBClustersRequest;
import com.amazonaws.services.rds.model.DescribeDBClustersResult;
import com.amazonaws.services.rds.model.DescribeDBInstancesRequest;
import com.amazonaws.services.rds.model.DescribeDBInstancesResult;
import com.amazonaws.services.rds.model.DescribeDBSnapshotsRequest;
import com.amazonaws.services.rds.model.DescribeDBSnapshotsResult;
import com.amazonaws.services.rds.model.ListTagsForResourceRequest;
import com.amazonaws.services.rds.model.ListTagsForResourceResult;
import com.pearson.eidetic.aws.RDSClientMethods;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RDSClientMethods_ESTest extends RDSClientMethods_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer(1758);
      // Undeclared exception!
      try { 
        RDSClientMethods.createTags((AmazonRDSClient) null, (AddTagsToResourceRequest) null, integer0, integer0, "PendingMaintenanceActionDetails: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer((-1557));
      Integer integer1 = new Integer((-1557));
      RDSClientMethods.createTags((AmazonRDSClient) null, (AddTagsToResourceRequest) null, integer1, integer0, (String) null);
      assertTrue(integer1.equals((Object)integer0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer(308);
      // Undeclared exception!
      try { 
        RDSClientMethods.createDBClusterSnapshot((AmazonRDS) null, (CreateDBClusterSnapshotRequest) null, integer0, integer0, "_uYKdEM%~tB>");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer((-8));
      Integer integer1 = new Integer((-8));
      DBClusterSnapshot dBClusterSnapshot0 = RDSClientMethods.createDBClusterSnapshot((AmazonRDS) null, (CreateDBClusterSnapshotRequest) null, integer0, integer1, "jF^VxtAav1y.");
      assertNull(dBClusterSnapshot0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Integer integer0 = new Integer(2317);
      // Undeclared exception!
      try { 
        RDSClientMethods.deleteDBClusterSnapshot((AmazonRDS) null, (DeleteDBClusterSnapshotRequest) null, integer0, integer0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Integer integer0 = new Integer(11);
      // Undeclared exception!
      try { 
        RDSClientMethods.deleteDBSnapshot((AmazonRDS) null, (DeleteDBSnapshotRequest) null, integer0, integer0, ")");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Integer integer0 = new Integer(1299);
      // Undeclared exception!
      try { 
        RDSClientMethods.deleteDBSnapshot((AmazonRDS) null, (DeleteDBSnapshotRequest) null, (Integer) null, integer0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Integer integer0 = new Integer(5271);
      // Undeclared exception!
      try { 
        RDSClientMethods.describeDBClusterSnapshots((AmazonRDS) null, (DescribeDBClusterSnapshotsRequest) null, integer0, integer0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Integer integer1 = new Integer((-1));
      DescribeDBClusterSnapshotsResult describeDBClusterSnapshotsResult0 = RDSClientMethods.describeDBClusterSnapshots((AmazonRDS) null, (DescribeDBClusterSnapshotsRequest) null, integer0, integer1, "com.amazonaws.services.rds.model.CopyDBParameterGroupRequest");
      assertNull(describeDBClusterSnapshotsResult0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Integer integer0 = new Integer(400);
      // Undeclared exception!
      try { 
        RDSClientMethods.describeDBSnapshots((AmazonRDS) null, (DescribeDBSnapshotsRequest) null, integer0, integer0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.describeDBSnapshots((AmazonRDS) null, (DescribeDBSnapshotsRequest) null, integer0, integer1, "7dw?h5ZT.+b%J'P");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer(730);
      Integer integer1 = new Integer(730);
      // Undeclared exception!
      try { 
        RDSClientMethods.describeDBClusters((AmazonRDS) null, (DescribeDBClustersRequest) null, integer0, integer1, "+26");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer(1);
      // Undeclared exception!
      try { 
        RDSClientMethods.getTags((AmazonRDS) null, (ListTagsForResourceRequest) null, integer0, integer0, ";");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.getTags((AmazonRDS) null, (ListTagsForResourceRequest) null, integer0, integer1, "/mEw2*$~Sz-U");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer(500);
      // Undeclared exception!
      try { 
        RDSClientMethods.describeDBInstances((AmazonRDS) null, (DescribeDBInstancesRequest) null, integer0, (Integer) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      Integer integer1 = new Integer(1210);
      // Undeclared exception!
      try { 
        RDSClientMethods.createDBSnapshot((AmazonRDS) null, (CreateDBSnapshotRequest) null, integer1, integer0, "com.amazonaws.services.rds.model.CopyDBParameterGroupRequest");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.createTags((AmazonRDSClient) null, (AddTagsToResourceRequest) null, integer0, integer0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.createDBClusterSnapshot((AmazonRDS) null, (CreateDBClusterSnapshotRequest) null, integer0, integer0, "ms%R Dr=OO[2m");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.createDBSnapshot((AmazonRDS) null, (CreateDBSnapshotRequest) null, integer0, (Integer) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Integer integer0 = new Integer((-572));
      DBSnapshot dBSnapshot0 = RDSClientMethods.createDBSnapshot((AmazonRDS) null, (CreateDBSnapshotRequest) null, integer0, integer0, "");
      assertNull(dBSnapshot0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Integer integer0 = new Integer((-572));
      Integer integer1 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.deleteDBClusterSnapshot((AmazonRDS) null, (DeleteDBClusterSnapshotRequest) null, integer1, integer0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Integer integer0 = new Integer((-773));
      RDSClientMethods.deleteDBClusterSnapshot((AmazonRDS) null, (DeleteDBClusterSnapshotRequest) null, integer0, integer0, "Eidetic_Interval");
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.deleteDBSnapshot((AmazonRDS) null, (DeleteDBSnapshotRequest) null, integer0, integer0, "<8wlW/");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Integer integer0 = new Integer((-773));
      RDSClientMethods.deleteDBSnapshot((AmazonRDS) null, (DeleteDBSnapshotRequest) null, integer0, integer0, "Eidetic_Interval");
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.describeDBClusterSnapshots((AmazonRDS) null, (DescribeDBClusterSnapshotsRequest) null, integer0, integer0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Integer integer0 = new Integer((-1816));
      DescribeDBSnapshotsResult describeDBSnapshotsResult0 = RDSClientMethods.describeDBSnapshots((AmazonRDS) null, (DescribeDBSnapshotsRequest) null, integer0, integer0, "com.amazonaws.services.rds.model.DescribeEventCategoriesResult");
      assertNull(describeDBSnapshotsResult0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.describeDBClusters((AmazonRDS) null, (DescribeDBClustersRequest) null, integer0, integer0, "Rl@'W0(`m,gc%Z7-c");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Integer integer0 = new Integer((-1816));
      DescribeDBClustersResult describeDBClustersResult0 = RDSClientMethods.describeDBClusters((AmazonRDS) null, (DescribeDBClustersRequest) null, integer0, integer0, "com.amazonaws.services.rds.model.DescribeEventCategoriesResult");
      assertNull(describeDBClustersResult0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Integer integer0 = new Integer((-773));
      ListTagsForResourceResult listTagsForResourceResult0 = RDSClientMethods.getTags((AmazonRDS) null, (ListTagsForResourceRequest) null, integer0, integer0, "Eidetic_Interval");
      assertNull(listTagsForResourceResult0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        RDSClientMethods.describeDBInstances((AmazonRDS) null, (DescribeDBInstancesRequest) null, integer0, integer0, "Xx#");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Integer integer0 = new Integer((-773));
      DescribeDBInstancesResult describeDBInstancesResult0 = RDSClientMethods.describeDBInstances((AmazonRDS) null, (DescribeDBInstancesRequest) null, integer0, integer0, "com.amazonaws.services.rds.model.DescribeDBLogFilesRequest");
      assertNull(describeDBInstancesResult0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      RDSClientMethods rDSClientMethods0 = new RDSClientMethods();
  }
}
