/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 04 21:31:16 GMT 2016
 */

package com.pearson.eidetic.globals;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.aws.AwsAccount;
import com.pearson.eidetic.globals.ApplicationConfiguration;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ApplicationConfiguration_ESTest extends ApplicationConfiguration_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      boolean boolean0 = ApplicationConfiguration.initialize((String) null);
      assertFalse(boolean0);
  }

  @Test
  public void test01()  throws Throwable  {
      String string0 = "Lop N2\\u";
      boolean boolean0 = ApplicationConfiguration.initialize(string0);
      assertFalse(boolean0);
  }

  @Test
  public void test02()  throws Throwable  {
      Integer integer0 = ApplicationConfiguration.getallSnapshotCleanKeepDays();
      assertNull(integer0);
  }

  @Test
  public void test03()  throws Throwable  {
      Boolean boolean0 = ApplicationConfiguration.getVolumeSynchronizer();
      assertNull(boolean0);
  }

  @Test
  public void test04()  throws Throwable  {
      Boolean boolean0 = ApplicationConfiguration.getEideticExpress();
      assertNull(boolean0);
  }

  @Test
  public void test05()  throws Throwable  {
      Boolean boolean0 = ApplicationConfiguration.getAmnesia();
      assertNull(boolean0);
  }

  @Test
  public void test06()  throws Throwable  {
      Boolean boolean0 = ApplicationConfiguration.getTagChecker();
      assertNull(boolean0);
  }

  @Test
  public void test07()  throws Throwable  {
      Integer integer0 = ApplicationConfiguration.geteideticCleanKeepDays();
      assertNull(integer0);
  }

  @Test
  public void test08()  throws Throwable  {
      Boolean boolean0 = ApplicationConfiguration.getSnapsPoller();
      assertNull(boolean0);
  }

  @Test
  public void test09()  throws Throwable  {
      Integer integer0 = ApplicationConfiguration.getSyncServerHttpListenerPort();
      assertNull(integer0);
  }

  @Test
  public void test10()  throws Throwable  {
      Boolean boolean0 = ApplicationConfiguration.getEidetic();
      assertNull(boolean0);
  }

  @Test
  public void test11()  throws Throwable  {
      Boolean boolean0 = ApplicationConfiguration.getErrorChecker();
      assertNull(boolean0);
  }

  @Test
  public void test12()  throws Throwable  {
      int int0 = ApplicationConfiguration.getAwsCallRetryAttempts();
      assertEquals((-4444), int0);
  }

  @Test
  public void test13()  throws Throwable  {
      ApplicationConfiguration applicationConfiguration0 = new ApplicationConfiguration();
      assertNull(applicationConfiguration0.getDefaultEideticTag());
  }

  @Test
  public void test14()  throws Throwable  {
      String string0 = ApplicationConfiguration.getDefaultEideticTag();
      assertNull(string0);
  }

  @Test
  public void test15()  throws Throwable  {
      Integer integer0 = ApplicationConfiguration.getrunTimeInterval();
      assertNull(integer0);
  }

  @Test
  public void test16()  throws Throwable  {
      List<AwsAccount> list0 = ApplicationConfiguration.getAwsAccounts();
      assertTrue(list0.isEmpty());
  }

  @Test
  public void test17()  throws Throwable  {
      Boolean boolean0 = ApplicationConfiguration.getEideticChecker();
      assertNull(boolean0);
  }
}
