/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 13 18:03:27 GMT 2015
 */

package com.pearson.eidetic.globals;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.globals.GlobalVariables;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class GlobalVariables_ESTest extends GlobalVariables_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      GlobalVariables globalVariables0 = new GlobalVariables();
  }
}
