/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 17:00:07 GMT 2017
 */

package com.pearson.eidetic.driver.threads.rds;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.pearson.eidetic.aws.AwsAccount;
import com.pearson.eidetic.driver.threads.rds.MonitorRDSTagPropagator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MonitorRDSTagPropagator_ESTest extends MonitorRDSTagPropagator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MonitorRDSTagPropagator monitorRDSTagPropagator0 = null;
      try {
        monitorRDSTagPropagator0 = new MonitorRDSTagPropagator((AwsAccount) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // null is not valid for AWSAccount
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.MonitorRDSTagPropagator", e);
      }
  }
}
