/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 28 16:54:21 GMT 2017
 */

package com.pearson.eidetic.driver.threads.rds;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MonitorRDSSnapshotNoTime_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.pearson.eidetic.driver.threads.rds.MonitorRDSSnapshotNoTime"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("os.name", "Mac OS X"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/Users/testuser"); 
    java.lang.System.setProperty("java.home", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre"); 
    java.lang.System.setProperty("user.dir", "/Users/testuser/Documents/NetBeansProjects/eidetic"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
    java.lang.System.setProperty("awt.toolkit", "sun.lwawt.macosx.LWCToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
    java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.CGraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.lwawt.macosx.CPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/EvoSuite_pathingJar8781735948883036538.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
    java.lang.System.setProperty("java.endorsed.dirs", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/Users/testuser/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_25-b17"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_25"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.version", "25.25-b02"); 
    java.lang.System.setProperty("os.arch", "x86_64"); 
    java.lang.System.setProperty("os.version", "10.10.5"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "testuser"); 
    java.lang.System.setProperty("user.timezone", "America/Chicago"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MonitorRDSSnapshotNoTime_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.http.client.methods.HttpPost",
      "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl",
      "org.apache.http.conn.scheme.LayeredSocketFactory",
      "com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector",
      "com.amazonaws.AmazonWebServiceClient",
      "org.apache.http.client.methods.HttpPatch",
      "com.amazonaws.metrics.RequestMetricCollector",
      "com.amazonaws.RequestClientOptions",
      "com.amazonaws.event.ProgressListener$1",
      "com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver",
      "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
      "com.amazonaws.event.ProgressListener",
      "com.amazonaws.internal.MetricAware",
      "org.apache.http.RequestLine",
      "com.fasterxml.jackson.databind.cfg.MapperConfigBase",
      "org.apache.http.HttpMessage",
      "org.apache.http.conn.ssl.SSLSocketFactory",
      "com.fasterxml.jackson.databind.JsonNode",
      "com.amazonaws.ResetException",
      "com.amazonaws.internal.ReleasableInputStream",
      "com.amazonaws.auth.AWSCredentials",
      "com.amazonaws.internal.CRC32MismatchException",
      "org.apache.http.HttpRequestInterceptor",
      "com.amazonaws.auth.profile.ProfileCredentialsProvider",
      "com.amazonaws.http.UnreliableTestConfig",
      "com.amazonaws.handlers.RequestHandler2",
      "com.amazonaws.metrics.RequestMetricCollector$1",
      "com.amazonaws.internal.config.SignerConfig",
      "org.apache.http.conn.HttpInetSocketAddress",
      "com.amazonaws.AmazonServiceException",
      "com.fasterxml.jackson.databind.ObjectWriter",
      "org.apache.http.conn.scheme.SchemeSocketFactory",
      "org.apache.http.conn.ClientConnectionManager",
      "com.pearson.eidetic.driver.MonitorRDS",
      "com.amazonaws.regions.RegionUtils",
      "com.fasterxml.jackson.databind.type.TypeBase",
      "org.apache.http.HttpRequest",
      "com.amazonaws.Response",
      "com.fasterxml.jackson.databind.deser.BasicDeserializerFactory",
      "org.apache.http.conn.socket.ConnectionSocketFactory",
      "com.fasterxml.jackson.databind.ser.BasicSerializerFactory",
      "com.amazonaws.http.HttpResponseHandler",
      "com.fasterxml.jackson.databind.cfg.MapperConfig",
      "com.amazonaws.AmazonClientException",
      "com.amazonaws.internal.config.Builder",
      "com.amazonaws.auth.InstanceProfileCredentialsProvider",
      "org.apache.http.client.methods.Configurable",
      "com.fasterxml.jackson.databind.MappingJsonFactory",
      "com.pearson.eidetic.utilities.Threads",
      "org.apache.http.client.methods.HttpHead",
      "org.apache.http.params.AbstractHttpParams",
      "com.fasterxml.jackson.core.JsonGenerator",
      "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext",
      "com.fasterxml.jackson.databind.jsontype.SubtypeResolver",
      "com.amazonaws.SignableRequest",
      "com.amazonaws.internal.ResettableInputStream",
      "com.fasterxml.jackson.core.ObjectCodec",
      "com.amazonaws.services.rds.AmazonRDS",
      "org.apache.http.client.methods.HttpUriRequest",
      "com.amazonaws.util.json.Jackson",
      "com.amazonaws.regions.Regions",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "org.apache.http.client.methods.AbortableHttpRequest",
      "com.amazonaws.internal.Releasable",
      "org.apache.http.client.HttpClient",
      "org.apache.http.auth.Credentials",
      "com.amazonaws.auth.AWSCredentialsProvider",
      "com.amazonaws.http.ExecutionContext",
      "com.fasterxml.jackson.core.JsonGenerationException",
      "com.fasterxml.jackson.databind.JavaType",
      "org.apache.http.client.methods.AbstractExecutionAwareRequest",
      "com.amazonaws.Protocol",
      "com.amazonaws.log.CommonsLog",
      "com.fasterxml.jackson.core.TreeNode",
      "com.amazonaws.http.AmazonHttpClient$ExecOneRequestParams",
      "com.fasterxml.jackson.core.TreeCodec",
      "com.fasterxml.jackson.databind.DeserializationContext",
      "com.amazonaws.log.JulLogFactory",
      "com.amazonaws.internal.SdkFilterInputStream",
      "org.apache.http.client.RedirectStrategy",
      "com.fasterxml.jackson.core.JsonFactory",
      "com.amazonaws.ClientConfiguration",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.amazonaws.log.CommonsLogFactory",
      "org.apache.http.protocol.HttpContext",
      "com.fasterxml.jackson.core.util.ByteArrayBuilder",
      "com.pearson.eidetic.aws.AwsAccount",
      "org.apache.http.params.HttpParams",
      "com.pearson.eidetic.driver.threads.rds.MonitorRDSSnapshotNoTime",
      "org.apache.http.HttpResponse",
      "com.amazonaws.util.ClassLoaderHelper",
      "com.fasterxml.jackson.databind.util.StdDateFormat",
      "com.amazonaws.internal.SdkBufferedInputStream",
      "com.amazonaws.internal.config.HttpClientConfig",
      "com.fasterxml.jackson.databind.util.TokenBuffer",
      "com.amazonaws.retry.RetryPolicy",
      "org.apache.http.client.methods.HttpEntityEnclosingRequestBase",
      "com.amazonaws.http.AmazonHttpClient",
      "org.apache.http.params.BasicHttpParams",
      "com.fasterxml.jackson.databind.AnnotationIntrospector",
      "com.fasterxml.jackson.core.Versioned",
      "org.apache.http.conn.scheme.LayeredSchemeSocketFactory",
      "org.apache.http.conn.scheme.SchemeLayeredSocketFactory",
      "org.apache.http.Header",
      "com.amazonaws.metrics.MetricType",
      "org.apache.http.concurrent.Cancellable",
      "org.apache.http.conn.ssl.X509HostnameVerifier",
      "com.fasterxml.jackson.databind.JsonSerializable",
      "com.amazonaws.handlers.RequestHandler2Adaptor",
      "com.fasterxml.jackson.core.JsonParseException",
      "com.amazonaws.handlers.RequestHandler",
      "org.apache.http.params.HttpParamsNames",
      "com.amazonaws.http.HttpRequestFactory",
      "com.amazonaws.util.FakeIOException",
      "org.apache.http.HttpEntity",
      "org.apache.http.client.methods.HttpRequestBase",
      "com.amazonaws.http.HttpResponse",
      "org.joda.time.ReadableInstant",
      "com.fasterxml.jackson.databind.deser.DeserializerFactory",
      "org.apache.http.conn.socket.LayeredConnectionSocketFactory",
      "org.apache.http.HttpResponseInterceptor",
      "org.apache.http.client.methods.HttpGet",
      "org.apache.http.conn.scheme.SocketFactory",
      "com.fasterxml.jackson.databind.JsonMappingException",
      "com.fasterxml.jackson.databind.introspect.ClassIntrospector$MixInResolver",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "com.amazonaws.util.AWSRequestMetrics",
      "com.amazonaws.internal.config.InternalConfigJsonHelper",
      "com.pearson.eidetic.driver.MonitorRDSMethods",
      "com.amazonaws.Request",
      "com.amazonaws.auth.AWSCredentialsProviderChain",
      "com.fasterxml.jackson.databind.ser.SerializerFactory",
      "com.fasterxml.jackson.databind.type.SimpleType",
      "com.amazonaws.util.VersionInfoUtils",
      "com.fasterxml.jackson.databind.DatabindContext",
      "org.apache.commons.logging.impl.Log4JLogger",
      "com.fasterxml.jackson.core.type.ResolvedType",
      "com.amazonaws.internal.config.JsonIndex",
      "org.apache.http.client.methods.HttpDelete",
      "com.fasterxml.jackson.databind.DeserializationConfig",
      "com.amazonaws.http.HttpClientFactory",
      "com.amazonaws.auth.Signer",
      "org.apache.http.message.AbstractHttpMessage",
      "com.fasterxml.jackson.databind.SerializerProvider",
      "com.amazonaws.AbortedException",
      "com.fasterxml.jackson.databind.deser.BeanDeserializerFactory",
      "org.apache.http.client.HttpRequestRetryHandler",
      "com.amazonaws.util.UnreliableFilterInputStream",
      "org.apache.http.HttpEntityEnclosingRequest",
      "com.amazonaws.AmazonWebServiceRequest$1",
      "com.amazonaws.AmazonWebServiceRequest",
      "com.amazonaws.util.TimingInfo",
      "com.fasterxml.jackson.databind.ser.BeanSerializerFactory",
      "com.fasterxml.jackson.databind.introspect.VisibilityChecker",
      "com.amazonaws.ResponseMetadata",
      "com.amazonaws.log.InternalLogFactory",
      "com.fasterxml.jackson.databind.ObjectMapper",
      "com.fasterxml.jackson.core.JsonProcessingException",
      "com.amazonaws.regions.RegionMetadataParser",
      "org.apache.http.client.methods.HttpExecutionAware",
      "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl",
      "com.amazonaws.http.conn.ssl.SdkTLSSocketFactory",
      "org.apache.http.client.methods.HttpPut",
      "com.amazonaws.regions.RegionMetadata",
      "com.amazonaws.util.CountingInputStream",
      "com.amazonaws.internal.config.InternalConfig",
      "com.amazonaws.internal.config.InternalConfig$Factory",
      "com.amazonaws.util.StringUtils",
      "com.amazonaws.RequestClientOptions$Marker",
      "com.amazonaws.ApacheHttpClientConfig",
      "com.fasterxml.jackson.core.PrettyPrinter",
      "com.amazonaws.regions.Region",
      "com.amazonaws.ReadLimitInfo",
      "com.amazonaws.log.InternalLogApi"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MonitorRDSSnapshotNoTime_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.pearson.eidetic.driver.threads.rds.MonitorRDSSnapshotNoTime",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.pearson.eidetic.utilities.Threads",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "com.pearson.eidetic.aws.AwsAccount",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "com.amazonaws.regions.RegionUtils",
      "com.amazonaws.regions.RegionMetadataParser",
      "com.amazonaws.regions.Region",
      "com.amazonaws.log.InternalLogFactory",
      "com.amazonaws.AmazonWebServiceClient",
      "com.amazonaws.util.VersionInfoUtils",
      "com.amazonaws.internal.config.InternalConfig",
      "com.amazonaws.util.ClassLoaderHelper",
      "com.amazonaws.util.json.Jackson",
      "com.amazonaws.internal.config.InternalConfig$Factory",
      "com.amazonaws.ClientConfiguration",
      "com.amazonaws.auth.AWSCredentialsProviderChain",
      "com.amazonaws.auth.profile.ProfileCredentialsProvider",
      "com.amazonaws.util.StringUtils",
      "com.amazonaws.auth.InstanceProfileCredentialsProvider",
      "com.amazonaws.http.HttpRequestFactory",
      "com.amazonaws.http.AmazonHttpClient",
      "org.apache.http.params.BasicHttpParams"
    );
  }
}
