/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 16:59:52 GMT 2017
 */

package com.pearson.eidetic.driver.threads.rds;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.amazonaws.services.rds.AmazonRDSClient;
import com.amazonaws.services.rds.model.DBCluster;
import com.amazonaws.services.rds.model.DBClusterSnapshot;
import com.amazonaws.services.rds.model.DBInstance;
import com.amazonaws.services.rds.model.DBSnapshot;
import com.amazonaws.services.rds.model.Tag;
import com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods;
import java.util.Collection;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.PeriodType;
import org.joda.time.format.ISOPeriodFormat;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RDSSubThreadMethods_ESTest extends RDSSubThreadMethods_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      RDSSubThreadMethods rDSSubThreadMethods1 = new RDSSubThreadMethods();
      rDSSubThreadMethods1.getDaysBetweenNowAndNewestDBClusterSnapshot((List<DBClusterSnapshot>) null);
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer(0);
      List<DBClusterSnapshot> list0 = rDSSubThreadMethods1.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer1, "<e3(OKi");
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBClusterSnapshot(list0);
      rDSSubThreadMethods0.getDaysBetweenNowAndNewestDBClusterSnapshot(list0);
      PeriodType.days();
      rDSSubThreadMethods1.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer1, integer0, "<e3(OKi");
      // Undeclared exception!
      try { 
        rDSSubThreadMethods1.getMinutesBetweenNowAndDBSnapshot((DBSnapshot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Parameter Snapshot cannot be null
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      RDSSubThreadMethods rDSSubThreadMethods1 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        rDSSubThreadMethods1.deleteDBClusterSnapshot((AmazonRDSClient) null, (DBClusterSnapshot) null, integer0, integer0, "CF");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer((-1269));
      Integer integer1 = new Integer((-1269));
      Integer integer2 = new Integer(12825000);
      Integer integer3 = new Integer(110);
      PeriodType.days();
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      rDSSubThreadMethods0.sortDBClusterSnapshotsByDate((List<DBClusterSnapshot>) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      rDSSubThreadMethods0.sortDBSnapshotsByDate((List<DBSnapshot>) null);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(1028);
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBClusterSnapshot((List<DBClusterSnapshot>) null);
      Integer integer1 = new Integer(0);
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.createDBClusterSnapshotOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer1, "Parameter Snapshot cannot be null");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(719527);
      Integer integer1 = new Integer(875);
      // Undeclared exception!
      try { 
        RDSSubThreadMethods.range(integer0, integer1);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(40);
      Integer integer1 = new Integer(0);
      Integer integer2 = new Integer(40);
      rDSSubThreadMethods0.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer2, integer2, "");
      List<DBSnapshot> list0 = rDSSubThreadMethods0.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer0, integer1, "");
      rDSSubThreadMethods0.getDaysBetweenNowAndNewestDBSnapshot(list0);
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.dateCompare((DBClusterSnapshot) null, (DBClusterSnapshot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(10080);
      Integer integer1 = new Integer(875);
      Integer integer2 = new Integer((-1));
      Integer integer3 = new Integer((-1062));
      rDSSubThreadMethods0.setResourceTags((AmazonRDSClient) null, (String) null, (Collection<Tag>) null, integer2, integer3, "PNT");
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.deleteDBSnapshot((AmazonRDSClient) null, (DBSnapshot) null, integer0, integer1, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(43);
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.deleteDBSnapshot((AmazonRDSClient) null, (DBSnapshot) null, integer0, integer0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      rDSSubThreadMethods0.getDaysBetweenNowAndNewestDBSnapshot((List<DBSnapshot>) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        RDSSubThreadMethods.range((Integer) null, (Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Parameter start/length cannot be null
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(0);
      List<DBSnapshot> list0 = rDSSubThreadMethods0.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer0, integer0, "Not supported yet.");
      rDSSubThreadMethods0.sortDBSnapshotsByDate(list0);
      Integer integer1 = new Integer(Integer.MAX_VALUE);
      Integer integer2 = new Integer(0);
      List<DBSnapshot> list1 = rDSSubThreadMethods0.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer1, integer2, "");
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBSnapshot(list1);
      PeriodType.days();
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.getMinutesBetweenNowAndDBClusterSnapshot((DBClusterSnapshot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Parameter Snapshot cannot be null
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(14);
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.getResourceTags((AmazonRDSClient) null, "", integer0, integer0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer((-1503));
      Integer integer1 = new Integer((-1503));
      List<DBSnapshot> list0 = rDSSubThreadMethods0.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer0, integer1, ":{X;=xM!1R=5$");
      rDSSubThreadMethods0.sortDBSnapshotsByDate(list0);
      Integer integer2 = new Integer((-1503));
      RDSSubThreadMethods.range(integer2, integer2);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      AmazonRDSClient amazonRDSClient0 = null;
      DBCluster dBCluster0 = null;
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer((-12));
      List<DBClusterSnapshot> list0 = rDSSubThreadMethods0.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer1, "+R|nZv[\"h;X");
      rDSSubThreadMethods0.sortDBClusterSnapshotsByDate(list0);
      DBClusterSnapshot dBClusterSnapshot0 = null;
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.getDaysBetweenNowAndDBClusterSnapshot((DBClusterSnapshot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Parameter Snapshot cannot be null
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(1);
      Integer integer1 = new Integer(1);
      List<DBSnapshot> list0 = rDSSubThreadMethods0.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer0, integer1, "!.H@g{}iSq!TewR-Jt");
      rDSSubThreadMethods0.getDaysBetweenNowAndNewestDBSnapshot(list0);
      RDSSubThreadMethods rDSSubThreadMethods1 = new RDSSubThreadMethods();
      RDSSubThreadMethods.range(integer0, integer1);
      Integer integer2 = new Integer((-1));
      Integer integer3 = new Integer(1);
      List<DBClusterSnapshot> list1 = rDSSubThreadMethods1.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer2, integer3, "awsAccountNickname=\"");
      rDSSubThreadMethods0.sortDBClusterSnapshotsByDate(list1);
      RDSSubThreadMethods.range(integer3, integer0);
      PeriodType.minutes();
      ISOPeriodFormat.standard();
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBSnapshot(list0);
      rDSSubThreadMethods1.getHoursBetweenNowAndNewestDBClusterSnapshot(list1);
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBSnapshot(list0);
      List<DBClusterSnapshot> list2 = rDSSubThreadMethods0.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer3, integer1, "h(&rS2*dhKr|q@lKE");
      rDSSubThreadMethods1.getDaysBetweenNowAndNewestDBClusterSnapshot(list2);
      Integer integer4 = new Integer(1992);
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.getResourceTags((AmazonRDSClient) null, ".<QXL#{:WR", (Integer) null, integer4, "1");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.aws.RDSClientMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      AmazonRDSClient amazonRDSClient0 = null;
      DBCluster dBCluster0 = null;
      int int0 = 2063;
      Integer integer0 = new Integer(2063);
      Integer integer1 = new Integer(2063);
      String string0 = "";
      List<DBClusterSnapshot> list0 = rDSSubThreadMethods0.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer1, "");
      rDSSubThreadMethods0.sortDBClusterSnapshotsByDate(list0);
      DBSnapshot dBSnapshot0 = null;
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.getDaysBetweenNowAndDBSnapshot((DBSnapshot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Parameter Snapshot cannot be null
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(20);
      Integer integer1 = new Integer(4219);
      List<DBClusterSnapshot> list0 = rDSSubThreadMethods0.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer1, "BoM;Y*l3AjH");
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBClusterSnapshot(list0);
      AmazonRDSClient amazonRDSClient0 = null;
      Integer integer2 = new Integer(1195);
      Integer integer3 = new Integer(251);
      List<DBSnapshot> list1 = rDSSubThreadMethods0.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer2, integer3, "");
      rDSSubThreadMethods0.sortDBSnapshotsByDate(list1);
      PeriodType.days();
      Integer integer4 = new Integer(1195);
      Integer integer5 = new Integer(0);
      String string0 = null;
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.createDBSnapshotOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer4, integer5, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      AmazonRDSClient amazonRDSClient0 = null;
      DBInstance dBInstance0 = null;
      Integer integer0 = null;
      Integer integer1 = new Integer((-1420));
      List<DBSnapshot> list0 = rDSSubThreadMethods0.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer1, integer1, "");
      rDSSubThreadMethods0.sortDBSnapshotsByDate(list0);
      List<DBSnapshot> list1 = rDSSubThreadMethods0.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, (Integer) null, (Integer) null, "");
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBSnapshot(list1);
      Integer integer2 = new Integer((-1));
      String string0 = "";
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.isFinished();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Not supported yet.
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      RDSSubThreadMethods rDSSubThreadMethods1 = new RDSSubThreadMethods();
      AmazonRDSClient amazonRDSClient0 = null;
      DBCluster dBCluster0 = null;
      Integer integer0 = new Integer(5083);
      Integer integer1 = new Integer(5083);
      String string0 = "";
      List<DBClusterSnapshot> list0 = rDSSubThreadMethods1.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer1, "");
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBClusterSnapshot(list0);
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.dateCompare((DBSnapshot) null, (DBSnapshot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      Integer integer0 = new Integer((-1344));
      List<DBClusterSnapshot> list0 = rDSSubThreadMethods0.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer0, "!+}pPA6'uf*q");
      rDSSubThreadMethods0.sortDBClusterSnapshotsByDate(list0);
      List<DBClusterSnapshot> list1 = rDSSubThreadMethods0.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, (Integer) null, (Integer) null, (String) null);
      rDSSubThreadMethods0.getDaysBetweenNowAndNewestDBClusterSnapshot(list1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      AmazonRDSClient amazonRDSClient0 = null;
      DBInstance dBInstance0 = null;
      int int0 = (-870);
      Integer integer0 = new Integer((-870));
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.createDBSnapshotOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer0, integer0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Integer integer0 = new Integer(538);
      RDSSubThreadMethods.range(integer0, integer0);
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      // Undeclared exception!
      try { 
        rDSSubThreadMethods0.createDBClusterSnapshotOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer0, "&@~4,F%!;yhfL+He`(\"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      RDSSubThreadMethods rDSSubThreadMethods0 = new RDSSubThreadMethods();
      RDSSubThreadMethods rDSSubThreadMethods1 = new RDSSubThreadMethods();
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer(0);
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBSnapshot((List<DBSnapshot>) null);
      Integer integer2 = new Integer((-3281));
      RDSSubThreadMethods.range(integer2, integer1);
      List<DBClusterSnapshot> list0 = rDSSubThreadMethods1.getAllDBClusterSnapshotsOfDBCluster((AmazonRDSClient) null, (DBCluster) null, integer0, integer1, "<e3(OKi");
      rDSSubThreadMethods0.getHoursBetweenNowAndNewestDBClusterSnapshot(list0);
      rDSSubThreadMethods0.getDaysBetweenNowAndNewestDBClusterSnapshot(list0);
      PeriodType.days();
      rDSSubThreadMethods1.getAllDBSnapshotsOfDBInstance((AmazonRDSClient) null, (DBInstance) null, integer1, integer0, "<e3(OKi");
      // Undeclared exception!
      try { 
        rDSSubThreadMethods1.getMinutesBetweenNowAndDBSnapshot((DBSnapshot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Parameter Snapshot cannot be null
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.RDSSubThreadMethods", e);
      }
  }
}
