/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 28 16:57:56 GMT 2017
 */

package com.pearson.eidetic.api;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SyncSnapshot_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.pearson.eidetic.api.SyncSnapshot"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("os.name", "Mac OS X"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/Users/testuser"); 
    java.lang.System.setProperty("java.home", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre"); 
    java.lang.System.setProperty("user.dir", "/Users/testuser/Documents/NetBeansProjects/eidetic"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
    java.lang.System.setProperty("awt.toolkit", "sun.lwawt.macosx.LWCToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
    java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.CGraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.lwawt.macosx.CPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/EvoSuite_pathingJar4560713932409568752.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
    java.lang.System.setProperty("java.endorsed.dirs", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/Users/testuser/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_25-b17"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_25"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.version", "25.25-b02"); 
    java.lang.System.setProperty("os.arch", "x86_64"); 
    java.lang.System.setProperty("os.version", "10.10.5"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "testuser"); 
    java.lang.System.setProperty("user.timezone", "America/Chicago"); 
    java.lang.System.setProperty("org.evosuite.shaded.org.dom4j.dom.DOMDocumentFactory.singleton.strategy", "org.evosuite.shaded.org.dom4j.util.SimpleSingleton"); 
    java.lang.System.setProperty("strategy", "EvoSuite"); 
    java.lang.System.setProperty("sun.java.launcher", "SUN_STANDARD"); 
    java.lang.System.setProperty("sun.management.compiler", "HotSpot 64-Bit Tiered Compilers"); 
    java.lang.System.setProperty("sun.boot.class.path", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/classes"); 
    java.lang.System.setProperty("show_progress", "false"); 
    java.lang.System.setProperty("extra_timeout", "10"); 
    java.lang.System.setProperty("process_communication_port", "15007"); 
    java.lang.System.setProperty("initialization_timeout", "10"); 
    java.lang.System.setProperty("org.evosuite.shaded.org.dom4j.factory", "org.evosuite.shaded.org.dom4j.DocumentFactory"); 
    java.lang.System.setProperty("assertion_timeout", "10"); 
    java.lang.System.setProperty("junit_tests", "true"); 
    java.lang.System.setProperty("log4j.configuration", "SUT.log4j.properties"); 
    java.lang.System.setProperty("analysis_criteria", ""); 
    java.lang.System.setProperty("sun.boot.library.path", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib"); 
    java.lang.System.setProperty("enable_asserts_for_evosuite", "false"); 
    java.lang.System.setProperty("sun.arch.data.model", "64"); 
    java.lang.System.setProperty("http.nonProxyHosts", "local|*.local|169.254/16|*.169.254/16"); 
    java.lang.System.setProperty("sun.cpu.isalist", ""); 
    java.lang.System.setProperty("sun.jnu.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.encoding.pkg", "sun.io"); 
    java.lang.System.setProperty("configuration_id", "default"); 
    java.lang.System.setProperty("PROJECT_PREFIX", ""); 
    java.lang.System.setProperty("ctg_time_per_class", "2"); 
    java.lang.System.setProperty("write_pool", "/Users/testuser/Documents/NetBeansProjects/eidetic/.evosuite/tmp_2017_06_28_11_45_53/pools/com.pearson.eidetic.api.SyncSnapshot.pool"); 
    java.lang.System.setProperty("save_all_data", "false"); 
    java.lang.System.setProperty("logback.configurationFile", "logback-ctg.xml"); 
    java.lang.System.setProperty("junit_check_timeout", "10"); 
    java.lang.System.setProperty("replace_calls", "true"); 
    java.lang.System.setProperty("coverage", "true"); 
    java.lang.System.setProperty("org.evosuite.shaded.org.dom4j.DocumentFactory.singleton.strategy", "org.evosuite.shaded.org.dom4j.util.SimpleSingleton"); 
    java.lang.System.setProperty("ctg_schedule", "BUDGET"); 
    java.lang.System.setProperty("sun.io.unicode.encoding", "UnicodeBig"); 
    java.lang.System.setProperty("socksNonProxyHosts", "local|*.local|169.254/16|*.169.254/16"); 
    java.lang.System.setProperty("ftp.nonProxyHosts", "local|*.local|169.254/16|*.169.254/16"); 
    java.lang.System.setProperty("stopping_condition", "MAXTIME"); 
    java.lang.System.setProperty("print_to_system", "false"); 
    java.lang.System.setProperty("ctg_seeds_file_in", "/Users/testuser/Documents/NetBeansProjects/eidetic/.evosuite/evosuite-seeds/com.pearson.eidetic.api.SyncSnapshot.seed"); 
    java.lang.System.setProperty("output_variables", "TARGET_CLASS,configuration_id,criterion,ctg_min_time_per_job,ctg_schedule,search_budget,p_object_pool,ctg_time_per_class,Size,Length,Total_Time,Random_Seed,LineCoverage,LineCoverageBitString,BranchCoverage,BranchCoverageBitString,ExceptionCoverage,ExceptionCoverageBitString,Explicit_MethodExceptions,Explicit_TypeExceptions,Implicit_MethodExceptions,Implicit_TypeExceptions,WeakMutationScore,WeakMutationCoverageBitString,OutputCoverage,OutputCoverageBitString,MethodCoverage,MethodCoverageBitString,MethodNoExceptionCoverage,MethodNoExceptionCoverageBitString,CBranchCoverage,CBranchCoverageBitString"); 
    java.lang.System.setProperty("global_timeout", "68"); 
    java.lang.System.setProperty("assertions", "true"); 
    java.lang.System.setProperty("log_timeout", "false"); 
    java.lang.System.setProperty("gopherProxySet", "false"); 
    java.lang.System.setProperty("master_log_port", "62416"); 
    java.lang.System.setProperty("reset_static_fields", "true"); 
    java.lang.System.setProperty("sun.java.command", "org.evosuite.ClientProcess"); 
    java.lang.System.setProperty("junit_check", "true"); 
    java.lang.System.setProperty("evosuite.log.folder", "/Users/testuser/Documents/NetBeansProjects/eidetic/.evosuite/tmp_2017_06_28_11_45_53/logs/com.pearson.eidetic.api.SyncSnapshot"); 
    java.lang.System.setProperty("minimize", "true"); 
    java.lang.System.setProperty("max_size", "100"); 
    java.lang.System.setProperty("sun.os.patch.level", "unknown"); 
    java.lang.System.setProperty("sun.cpu.endian", "little"); 
    java.lang.System.setProperty("ctg_min_time_per_job", "1"); 
    java.lang.System.setProperty("junit_suffix", "_ESTest"); 
    java.lang.System.setProperty("java.vendor.url.bug", "http://bugreport.sun.com/bugreport/"); 
    java.lang.System.setProperty("report_dir", "/Users/testuser/Documents/NetBeansProjects/eidetic/.evosuite/tmp_2017_06_28_11_45_53/reports/com.pearson.eidetic.api.SyncSnapshot"); 
    java.lang.System.setProperty("minimization_timeout", "10"); 
    java.lang.System.setProperty("CP_file_path", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/EvoSuite_classpathFile294176964125941739.txt"); 
    java.lang.System.setProperty("java.rmi.server.hostname", "127.0.0.1"); 
    java.lang.System.setProperty("inline", "true"); 
    java.lang.System.setProperty("ctg_seeds_file_out", "/Users/testuser/Documents/NetBeansProjects/eidetic/.evosuite/tmp_2017_06_28_11_45_53/seeds/com.pearson.eidetic.api.SyncSnapshot.seed"); 
    java.lang.System.setProperty("TARGET_CLASS", "com.pearson.eidetic.api.SyncSnapshot"); 
    java.lang.System.setProperty("spawn_process_manager_port", "62073"); 
    java.lang.System.setProperty("evosuite.log.appender", "CLIENT"); 
    java.lang.System.setProperty("write_junit_timeout", "10"); 
    java.lang.System.setProperty("test_dir", "/Users/testuser/Documents/NetBeansProjects/eidetic/.evosuite/tmp_2017_06_28_11_45_53/tests"); 
    java.lang.System.setProperty("search_budget", "68"); 
    java.lang.System.setProperty("plot", "false"); 
    java.lang.System.setProperty("p_object_pool", "0.3"); 
    java.lang.System.setProperty("criterion", "LINE:BRANCH:EXCEPTION:WEAKMUTATION:OUTPUT:METHOD:METHODNOEXCEPTION:CBRANCH"); 
    java.lang.System.setProperty("test_comments", "false"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SyncSnapshot_ESTest_scaffolding.class.getClassLoader() ,
      "com.amazonaws.AmazonWebServiceClient",
      "org.eclipse.jetty.util.ConcurrentHashSet",
      "org.eclipse.jetty.server.handler.AbstractHandlerContainer",
      "com.amazonaws.metrics.RequestMetricCollector",
      "com.pearson.eidetic.api.SyncSnapshot$1",
      "org.eclipse.jetty.util.thread.ExecutionStrategy$DefaultExecutionStrategyFactory",
      "org.eclipse.jetty.util.annotation.ManagedObject",
      "org.eclipse.jetty.util.MultiException",
      "org.eclipse.jetty.util.Callback",
      "com.amazonaws.auth.AWSCredentials",
      "com.amazonaws.handlers.RequestHandler2",
      "com.amazonaws.internal.config.SignerConfig",
      "com.fasterxml.jackson.databind.ObjectWriter",
      "com.amazonaws.regions.RegionUtils",
      "org.eclipse.jetty.servlet.Invoker",
      "org.eclipse.jetty.util.thread.ThreadPool",
      "com.amazonaws.Response",
      "com.amazonaws.services.ec2.model.VolumeState",
      "com.amazonaws.services.ec2.model.Tag",
      "org.eclipse.jetty.http.MimeTypes",
      "com.amazonaws.AmazonClientException",
      "org.eclipse.jetty.server.Handler",
      "com.amazonaws.internal.config.Builder",
      "org.eclipse.jetty.util.component.Destroyable",
      "com.pearson.eidetic.utilities.Threads",
      "org.eclipse.jetty.http.HttpGenerator$State",
      "com.fasterxml.jackson.core.ObjectCodec",
      "com.pearson.eidetic.api.SyncSnapshot",
      "org.eclipse.jetty.util.thread.ThreadPool$SizedThreadPool",
      "org.eclipse.jetty.util.StringUtil",
      "com.amazonaws.regions.Regions",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "org.eclipse.jetty.server.handler.ContextHandler$ContextScopeListener",
      "org.eclipse.jetty.util.TreeTrie",
      "org.eclipse.jetty.server.HttpConfiguration",
      "org.eclipse.jetty.server.handler.ContextHandler$Availability",
      "org.eclipse.jetty.servlet.ServletMapping",
      "com.fasterxml.jackson.core.TreeNode",
      "org.eclipse.jetty.http.HttpHeaderValue",
      "org.eclipse.jetty.server.RequestLog",
      "org.eclipse.jetty.server.ShutdownMonitor$Holder",
      "org.eclipse.jetty.util.component.Dumpable",
      "com.amazonaws.ClientConfiguration",
      "org.eclipse.jetty.servlet.Holder$1",
      "com.pearson.eidetic.utilities.StackTrace",
      "org.eclipse.jetty.util.resource.Resource",
      "com.amazonaws.log.CommonsLogFactory",
      "org.eclipse.jetty.io.Connection",
      "com.pearson.eidetic.aws.AwsAccount",
      "org.eclipse.jetty.util.thread.Locker",
      "org.eclipse.jetty.servlet.FilterMapping",
      "com.amazonaws.util.ClassLoaderHelper",
      "com.amazonaws.internal.config.HttpClientConfig",
      "com.amazonaws.retry.RetryPolicy",
      "com.fasterxml.jackson.core.Versioned",
      "org.eclipse.jetty.util.component.ContainerLifeCycle$Bean",
      "org.eclipse.jetty.servlet.DefaultServlet",
      "com.amazonaws.util.IOUtils",
      "org.eclipse.jetty.io.SelectorManager",
      "org.eclipse.jetty.util.component.Container",
      "com.amazonaws.metrics.MetricType",
      "org.eclipse.jetty.server.ShutdownMonitor$ShutdownMonitorRunnable",
      "org.eclipse.jetty.servlet.ServletHandler$Default404Servlet",
      "org.eclipse.jetty.http.HttpGenerator$1",
      "org.eclipse.jetty.server.handler.ContextHandler$Context",
      "org.eclipse.jetty.servlet.FilterHolder",
      "org.eclipse.jetty.util.thread.QueuedThreadPool",
      "org.eclipse.jetty.server.handler.AllowSymLinkAliasChecker",
      "com.fasterxml.jackson.databind.JsonSerializable",
      "org.eclipse.jetty.http.HttpStatus",
      "org.eclipse.jetty.util.ConcurrentArrayQueue$Block",
      "org.eclipse.jetty.servlet.ServletHandler",
      "org.eclipse.jetty.util.QuotedStringTokenizer",
      "org.eclipse.jetty.server.ShutdownMonitor",
      "org.eclipse.jetty.server.handler.ContextHandler$StaticContext",
      "org.eclipse.jetty.util.component.Graceful",
      "org.eclipse.jetty.servlets.CGI",
      "org.eclipse.jetty.util.component.Container$Listener",
      "org.eclipse.jetty.http.HttpGenerator",
      "org.eclipse.jetty.util.Trie",
      "org.eclipse.jetty.util.thread.ExecutionStrategy$Factory",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "org.eclipse.jetty.servlet.Holder$HolderConfig",
      "org.eclipse.jetty.servlets.ConcatServlet",
      "org.eclipse.jetty.http.BadMessageException",
      "org.eclipse.jetty.util.AttributesMap",
      "org.eclipse.jetty.server.handler.AbstractHandler",
      "org.eclipse.jetty.servlet.BaseHolder",
      "org.eclipse.jetty.util.resource.ResourceFactory",
      "org.eclipse.jetty.servlet.ServletHolder$Config",
      "org.json.simple.parser.ContentHandler",
      "org.eclipse.jetty.util.log.AbstractLogger",
      "org.eclipse.jetty.util.thread.Locker$Lock",
      "org.eclipse.jetty.http.HttpGenerator$Result",
      "org.eclipse.jetty.http.PathMap",
      "org.eclipse.jetty.http.HttpFields",
      "com.amazonaws.log.InternalLogFactory",
      "com.fasterxml.jackson.core.JsonProcessingException",
      "org.eclipse.jetty.util.thread.ExecutionStrategy",
      "org.eclipse.jetty.http.HttpMethod",
      "org.eclipse.jetty.util.log.Log",
      "com.amazonaws.internal.config.InternalConfig$Factory",
      "org.eclipse.jetty.server.handler.ScopedHandler",
      "org.eclipse.jetty.http.MetaData$Request",
      "org.eclipse.jetty.util.log.Logger",
      "org.eclipse.jetty.server.Connector",
      "com.amazonaws.ReadLimitInfo",
      "org.eclipse.jetty.util.component.ContainerLifeCycle$1",
      "org.eclipse.jetty.server.Request",
      "org.eclipse.jetty.servlet.BaseHolder$Source",
      "org.eclipse.jetty.io.EofException",
      "org.eclipse.jetty.servlets.DataRateLimitedServlet",
      "org.eclipse.jetty.util.component.ContainerLifeCycle",
      "org.eclipse.jetty.server.handler.ErrorHandler",
      "org.json.simple.parser.Yytoken",
      "org.eclipse.jetty.util.AbstractTrie",
      "com.fasterxml.jackson.databind.JsonNode",
      "org.eclipse.jetty.server.Server",
      "org.eclipse.jetty.util.BlockingArrayQueue",
      "org.eclipse.jetty.servlet.ServletHolder$1",
      "org.eclipse.jetty.server.HandlerContainer",
      "org.eclipse.jetty.http.HttpContent",
      "org.eclipse.jetty.http.MimeTypes$Type",
      "org.eclipse.jetty.util.component.AbstractLifeCycle",
      "org.json.simple.parser.ContainerFactory",
      "org.eclipse.jetty.util.MultiPartOutputStream",
      "org.eclipse.jetty.servlet.ServletHolder",
      "org.eclipse.jetty.util.ConcurrentArrayQueue",
      "org.eclipse.jetty.util.log.JettyAwareLogger",
      "org.eclipse.jetty.http.PreEncodedHttpField",
      "org.eclipse.jetty.util.BufferUtil",
      "org.eclipse.jetty.server.Response",
      "org.eclipse.jetty.util.MemoryUtils",
      "com.fasterxml.jackson.core.JsonGenerator",
      "org.eclipse.jetty.http.HttpStatus$Code",
      "org.eclipse.jetty.server.SessionIdManager",
      "org.eclipse.jetty.security.IdentityService",
      "com.amazonaws.SignableRequest",
      "com.amazonaws.services.rds.AmazonRDS",
      "org.eclipse.jetty.util.ArrayTrie",
      "com.amazonaws.util.json.Jackson",
      "org.eclipse.jetty.servlet.StatisticsServlet",
      "org.eclipse.jetty.http.PathMap$MappedEntry",
      "com.amazonaws.auth.AWSCredentialsProvider",
      "com.amazonaws.http.ExecutionContext",
      "com.amazonaws.services.ec2.model.Volume",
      "org.eclipse.jetty.util.component.LifeCycle$Listener",
      "com.amazonaws.Protocol",
      "org.eclipse.jetty.server.UserIdentity$Scope",
      "com.fasterxml.jackson.core.TreeCodec",
      "com.amazonaws.log.JulLogFactory",
      "org.eclipse.jetty.util.ArrayTernaryTrie",
      "org.eclipse.jetty.util.ArrayUtil",
      "org.eclipse.jetty.server.HttpConfiguration$Customizer",
      "com.amazonaws.services.ec2.model.VolumeType",
      "org.eclipse.jetty.util.Attributes",
      "org.eclipse.jetty.util.component.LifeCycle",
      "org.eclipse.jetty.io.EndPoint",
      "org.eclipse.jetty.http.MetaData$Response",
      "org.eclipse.jetty.util.Uptime$Impl",
      "org.eclipse.jetty.server.handler.ContextHandler$AliasCheck",
      "org.eclipse.jetty.http.MetaData",
      "org.eclipse.jetty.servlet.NoJspServlet",
      "org.eclipse.jetty.io.RuntimeIOException",
      "com.fasterxml.jackson.core.JsonParseException",
      "org.eclipse.jetty.util.Jetty",
      "org.eclipse.jetty.http.HttpCompliance",
      "com.amazonaws.handlers.RequestHandler",
      "org.json.simple.parser.JSONParser",
      "org.eclipse.jetty.util.component.ContainerLifeCycle$Managed",
      "org.json.simple.parser.Yylex",
      "org.eclipse.jetty.servlet.JspPropertyGroupServlet",
      "org.eclipse.jetty.servlet.Holder",
      "org.eclipse.jetty.servlet.ListenerHolder",
      "com.fasterxml.jackson.databind.JsonMappingException",
      "com.amazonaws.util.AWSRequestMetrics",
      "com.amazonaws.internal.config.InternalConfigJsonHelper",
      "org.eclipse.jetty.util.Uptime",
      "com.amazonaws.Request",
      "org.eclipse.jetty.http.HttpScheme",
      "org.eclipse.jetty.server.HttpChannel",
      "org.eclipse.jetty.http.HttpVersion",
      "org.eclipse.jetty.util.thread.Scheduler",
      "com.amazonaws.util.VersionInfoUtils",
      "org.eclipse.jetty.io.ManagedSelector",
      "com.amazonaws.internal.config.JsonIndex",
      "org.eclipse.jetty.http.HttpHeader",
      "org.json.simple.parser.ParseException",
      "com.amazonaws.auth.Signer",
      "com.amazonaws.AmazonWebServiceRequest",
      "org.eclipse.jetty.server.handler.ContextHandler$ApproveNonExistentDirectoryAliases",
      "com.fasterxml.jackson.databind.ObjectMapper",
      "org.eclipse.jetty.server.HttpOutput$Interceptor",
      "org.eclipse.jetty.server.handler.HandlerWrapper",
      "org.eclipse.jetty.server.handler.ContextHandler",
      "com.amazonaws.regions.RegionMetadataParser",
      "org.eclipse.jetty.util.thread.ExecutionStrategy$Producer",
      "com.amazonaws.regions.RegionMetadata",
      "org.eclipse.jetty.http.HttpField",
      "com.amazonaws.internal.config.InternalConfig",
      "org.eclipse.jetty.io.WriterOutputStream",
      "com.amazonaws.ApacheHttpClientConfig",
      "org.eclipse.jetty.server.handler.ContextHandler$ApproveAliases",
      "org.eclipse.jetty.http.HttpContent$Factory",
      "com.amazonaws.regions.Region",
      "com.amazonaws.services.ec2.model.VolumeAttachment",
      "com.amazonaws.log.InternalLogApi"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SyncSnapshot_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.pearson.eidetic.api.SyncSnapshot$1",
      "com.amazonaws.regions.Regions",
      "com.pearson.eidetic.api.SyncSnapshot",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "com.amazonaws.regions.RegionUtils",
      "com.amazonaws.util.IOUtils",
      "com.pearson.eidetic.utilities.Threads",
      "org.eclipse.jetty.servlet.ServletHandler$Default404Servlet",
      "org.eclipse.jetty.util.log.Log",
      "org.eclipse.jetty.util.log.AbstractLogger",
      "org.eclipse.jetty.util.log.JettyAwareLogger",
      "org.eclipse.jetty.util.Uptime",
      "org.eclipse.jetty.util.component.AbstractLifeCycle",
      "org.eclipse.jetty.util.component.ContainerLifeCycle",
      "org.eclipse.jetty.server.handler.AbstractHandler",
      "org.eclipse.jetty.server.handler.ScopedHandler",
      "org.eclipse.jetty.server.Server",
      "org.eclipse.jetty.util.Jetty",
      "org.eclipse.jetty.server.handler.ContextHandler",
      "org.eclipse.jetty.servlet.ServletHandler",
      "org.eclipse.jetty.servlet.JspPropertyGroupServlet",
      "org.json.simple.parser.JSONParser",
      "org.json.simple.parser.Yylex",
      "org.eclipse.jetty.servlets.CGI",
      "org.eclipse.jetty.servlets.DataRateLimitedServlet",
      "org.eclipse.jetty.servlets.ConcatServlet",
      "org.eclipse.jetty.servlet.NoJspServlet",
      "org.eclipse.jetty.http.HttpField",
      "org.eclipse.jetty.http.PreEncodedHttpField",
      "org.eclipse.jetty.util.ArrayTrie",
      "org.eclipse.jetty.util.StringUtil",
      "org.eclipse.jetty.http.HttpHeader",
      "org.eclipse.jetty.http.HttpVersion",
      "org.eclipse.jetty.servlet.DefaultServlet",
      "org.eclipse.jetty.servlet.Invoker",
      "org.eclipse.jetty.servlet.StatisticsServlet",
      "org.eclipse.jetty.server.handler.AllowSymLinkAliasChecker",
      "com.pearson.eidetic.aws.AwsAccount",
      "com.amazonaws.regions.RegionMetadataParser",
      "com.amazonaws.regions.Region",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "com.amazonaws.log.InternalLogFactory",
      "com.amazonaws.AmazonWebServiceClient",
      "com.amazonaws.util.VersionInfoUtils",
      "com.amazonaws.internal.config.InternalConfig",
      "com.amazonaws.util.ClassLoaderHelper",
      "com.amazonaws.util.json.Jackson",
      "com.amazonaws.internal.config.InternalConfig$Factory",
      "com.amazonaws.ClientConfiguration",
      "org.eclipse.jetty.util.thread.Locker",
      "org.eclipse.jetty.util.thread.QueuedThreadPool",
      "org.eclipse.jetty.util.MemoryUtils",
      "org.eclipse.jetty.util.BlockingArrayQueue",
      "org.eclipse.jetty.util.component.ContainerLifeCycle$Managed",
      "org.eclipse.jetty.util.component.ContainerLifeCycle$1",
      "org.eclipse.jetty.servlet.BaseHolder",
      "org.eclipse.jetty.servlet.Holder",
      "org.eclipse.jetty.servlet.ServletHolder",
      "org.eclipse.jetty.servlet.Holder$1",
      "org.eclipse.jetty.util.ArrayUtil",
      "org.eclipse.jetty.http.PathMap",
      "org.eclipse.jetty.util.ArrayTernaryTrie",
      "org.eclipse.jetty.util.MultiException",
      "org.eclipse.jetty.server.ShutdownMonitor$Holder",
      "org.eclipse.jetty.server.HttpConfiguration",
      "org.eclipse.jetty.util.BufferUtil",
      "org.eclipse.jetty.http.HttpHeaderValue",
      "org.eclipse.jetty.http.HttpFields",
      "org.eclipse.jetty.http.HttpMethod",
      "org.eclipse.jetty.http.HttpStatus$Code",
      "org.eclipse.jetty.http.HttpStatus",
      "org.eclipse.jetty.http.HttpGenerator",
      "org.eclipse.jetty.server.handler.ContextHandler$Availability",
      "org.eclipse.jetty.http.MimeTypes$Type",
      "org.eclipse.jetty.http.MimeTypes",
      "com.amazonaws.services.ec2.model.Volume",
      "org.eclipse.jetty.util.TreeTrie",
      "org.eclipse.jetty.http.HttpScheme",
      "org.eclipse.jetty.http.HttpCompliance",
      "org.eclipse.jetty.util.ConcurrentArrayQueue",
      "org.eclipse.jetty.util.ConcurrentArrayQueue$Block",
      "org.eclipse.jetty.io.SelectorManager",
      "org.eclipse.jetty.util.thread.ExecutionStrategy$DefaultExecutionStrategyFactory"
    );
  }
}
