/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 16:52:28 GMT 2017
 */

package com.pearson.eidetic.driver.threads.rds.subthreads;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.rds.AmazonRDSClient;
import com.amazonaws.services.rds.model.DBInstance;
import com.pearson.eidetic.driver.threads.rds.subthreads.RDSSnapshotDBInstanceNoTime;
import java.util.ArrayList;
import java.util.Date;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.json.simple.JSONObject;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RDSSnapshotDBInstanceNoTime_ESTest extends RDSSnapshotDBInstanceNoTime_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer(530);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime((String) null, (String) null, (String) null, (String) null, integer0, integer0, (Region) null, arrayList0);
      JSONObject jSONObject0 = new JSONObject();
      DBInstance dBInstance0 = new DBInstance();
      rDSSnapshotDBInstanceNoTime0.getPeriod(jSONObject0, dBInstance0);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(407);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("T", "w}?)D", "yc~kGn?pi+S@WDuC8A", "yc~kGn?pi+S@WDuC8A", integer0, integer0, (Region) null, arrayList0);
      // Undeclared exception!
      try { 
        rDSSnapshotDBInstanceNoTime0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.subthreads.RDSSnapshotDBInstanceNoTime", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Regions regions0 = Regions.CN_NORTH_1;
      Region region0 = Region.getRegion(regions0);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("Tp'=|kv", "Unable to parse clock skew offset from response: ", "Tp'=|kv", "", integer0, integer0, region0, arrayList0);
      // Undeclared exception!
      try { 
        rDSSnapshotDBInstanceNoTime0.run();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class com.amazonaws.ClientConfiguration
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.subthreads.RDSSnapshotDBInstanceNoTime", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer(9);
      Regions regions0 = Regions.GovCloud;
      Region region0 = Region.getRegion(regions0);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime((String) null, (String) null, "[As~(!CqXRY#W<#94t*", "[As~(!CqXRY#W<#94t*", integer0, integer0, region0, arrayList0);
      // Undeclared exception!
      try { 
        rDSSnapshotDBInstanceNoTime0.run();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Access key cannot be null.
         //
         verifyException("com.amazonaws.auth.BasicAWSCredentials", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("\", \"snapshot\"=\"", "\", \"snapshot\"=\"", "\", \"snapshot\"=\"", "\", \"snapshot\"=\"", (Integer) null, (Integer) null, (Region) null, arrayList0);
      // Undeclared exception!
      try { 
        rDSSnapshotDBInstanceNoTime0.connect((Region) null, "week_snapshot", "\", \"snapshot\"=\"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.subthreads.RDSSnapshotDBInstanceNoTime", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Integer integer0 = new Integer(2977);
      Regions regions0 = Regions.US_WEST_1;
      Region region0 = Region.getRegion(regions0);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("", "\",Event=\"Error\", Error=\"error creating snapshot from dbInstance\", DBInstance_Identifier=\"", "", "", integer0, (Integer) null, region0, arrayList0);
      // Undeclared exception!
      try { 
        rDSSnapshotDBInstanceNoTime0.connect(region0, "\",Event=\"Error\", Error=\"error creating snapshot from dbInstance\", DBInstance_Identifier=\"", "No file name has been set!");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class com.amazonaws.ClientConfiguration
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.subthreads.RDSSnapshotDBInstanceNoTime", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Integer integer0 = new Integer(20);
      Regions regions0 = Regions.CN_NORTH_1;
      Region region0 = Region.getRegion(regions0);
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", integer0, integer0, region0, (ArrayList<DBInstance>) null);
      boolean boolean0 = rDSSnapshotDBInstanceNoTime0.snapshotDeletion((AmazonRDSClient) null, (DBInstance) null, "zh+%OaB&<QJp`6u", integer0);
      assertFalse(boolean0);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Integer integer0 = new Integer(1132);
      Regions regions0 = Regions.SA_EAST_1;
      Region region0 = Region.getRegion(regions0);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("", "", "", "", integer0, integer0, region0, arrayList0);
      DBInstance dBInstance0 = new DBInstance();
      boolean boolean0 = rDSSnapshotDBInstanceNoTime0.snapshotDeletion((AmazonRDSClient) null, dBInstance0, "", (Integer) null);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(20);
      Regions regions0 = Regions.CN_NORTH_1;
      Region region0 = Region.getRegion(regions0);
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", integer0, integer0, region0, (ArrayList<DBInstance>) null);
      boolean boolean0 = rDSSnapshotDBInstanceNoTime0.snapshotCreation((AmazonRDSClient) null, (DBInstance) null, "zh+%OaB&<QJp`6u", (Date) null);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Regions regions0 = Regions.AP_SOUTHEAST_2;
      Region region0 = Region.getRegion(regions0);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime(">]@o2t3WYbjx8~gD7)", ">]@o2t3WYbjx8~gD7)", ">]@o2t3WYbjx8~gD7)", ">]@o2t3WYbjx8~gD7)", (Integer) null, (Integer) null, region0, arrayList0);
      boolean boolean0 = rDSSnapshotDBInstanceNoTime0.snapshotDecision((AmazonRDSClient) null, (DBInstance) null, ">]@o2t3WYbjx8~gD7)");
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(530);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime((String) null, (String) null, (String) null, (String) null, integer0, integer0, (Region) null, arrayList0);
      JSONObject jSONObject0 = new JSONObject();
      DBInstance dBInstance0 = new DBInstance();
      rDSSnapshotDBInstanceNoTime0.getKeep(jSONObject0, dBInstance0);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = new Integer(20);
      Regions regions0 = Regions.CN_NORTH_1;
      Region region0 = Region.getRegion(regions0);
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", integer0, integer0, region0, (ArrayList<DBInstance>) null);
      rDSSnapshotDBInstanceNoTime0.getKeep((JSONObject) null, (DBInstance) null);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Regions regions0 = Regions.AP_SOUTHEAST_2;
      Region region0 = Region.getRegion(regions0);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime(">I@o2t3WYj8~gD7)", ">I@o2t3WYj8~gD7)", "v&!", "v&!", (Integer) null, (Integer) null, region0, arrayList0);
      JSONObject jSONObject0 = new JSONObject();
      rDSSnapshotDBInstanceNoTime0.getKeep(jSONObject0, (DBInstance) null);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer(407);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("T", "w}?)D", "yc~kGn?pi+S@WDuC8A", "yc~kGn?pi+S@WDuC8A", integer0, integer0, (Region) null, arrayList0);
      rDSSnapshotDBInstanceNoTime0.getPeriod((JSONObject) null, (DBInstance) null);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Regions regions0 = Regions.EU_CENTRAL_1;
      Region region0 = Region.getRegion(regions0);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("Sza", "Sza", "Sza", (String) null, (Integer) null, (Integer) null, region0, arrayList0);
      JSONObject jSONObject0 = new JSONObject();
      // Undeclared exception!
      try { 
        rDSSnapshotDBInstanceNoTime0.getPeriod(jSONObject0, (DBInstance) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.subthreads.RDSSnapshotDBInstanceNoTime", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Integer integer0 = new Integer(20);
      Regions regions0 = Regions.CN_NORTH_1;
      Region region0 = Region.getRegion(regions0);
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", integer0, integer0, region0, (ArrayList<DBInstance>) null);
      rDSSnapshotDBInstanceNoTime0.getIntTagValue((AmazonRDSClient) null, (DBInstance) null);
      assertFalse(rDSSnapshotDBInstanceNoTime0.isFinished());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Regions regions0 = Regions.CN_NORTH_1;
      Region region0 = Region.getRegion(regions0);
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", "zh+%OaB&<QJp`6u", integer0, integer0, region0, (ArrayList<DBInstance>) null);
      DBInstance dBInstance0 = new DBInstance();
      // Undeclared exception!
      try { 
        rDSSnapshotDBInstanceNoTime0.getIntTagValue((AmazonRDSClient) null, dBInstance0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.pearson.eidetic.driver.threads.rds.subthreads.RDSSnapshotDBInstanceNoTime", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("\", \"snapshot\"=\"", "\", \"snapshot\"=\"", "\", \"snapshot\"=\"", "\", \"snapshot\"=\"", (Integer) null, (Integer) null, (Region) null, arrayList0);
      boolean boolean0 = rDSSnapshotDBInstanceNoTime0.isFinished();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Regions regions0 = Regions.GovCloud;
      Region region0 = Region.getRegion(regions0);
      ArrayList<DBInstance> arrayList0 = new ArrayList<DBInstance>();
      RDSSnapshotDBInstanceNoTime rDSSnapshotDBInstanceNoTime0 = new RDSSnapshotDBInstanceNoTime("_snapshot ", "_snapshot ", "_snapshot ", "_snapshot ", (Integer) null, integer0, region0, arrayList0);
      // Undeclared exception!
      try { 
        rDSSnapshotDBInstanceNoTime0.connect(region0, "_snapshot ", (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Secret key cannot be null.
         //
         verifyException("com.amazonaws.auth.BasicAWSCredentials", e);
      }
  }
}
