/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 04 20:52:39 GMT 2016
 */

package com.pearson.eidetic.driver.threads.subthreads;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.amazonaws.regions.Region;
import com.amazonaws.services.ec2.model.Volume;
import com.pearson.eidetic.driver.threads.subthreads.SnapshotChecker;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SnapshotChecker_ESTest extends SnapshotChecker_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      ArrayList<Volume> arrayList0 = new ArrayList<Volume>();
      SnapshotChecker snapshotChecker0 = new SnapshotChecker("week", "week", "week", integer0, integer0, (Region) null, arrayList0, arrayList0);
      // Undeclared exception!
      try { 
        snapshotChecker0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.pearson.eidetic.driver.threads.subthreads.SnapshotChecker", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(1590);
      ArrayList<Volume> arrayList0 = new ArrayList<Volume>();
      SnapshotChecker snapshotChecker0 = new SnapshotChecker("t9", "t9", (String) null, integer0, integer0, (Region) null, arrayList0, arrayList0);
      // Undeclared exception!
      try { 
        snapshotChecker0.connect((Region) null, "t9", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.pearson.eidetic.driver.threads.subthreads.SnapshotChecker", e);
      }
  }
}
