/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 04 21:24:54 GMT 2016
 */

package com.pearson.eidetic.driver.threads.subthreads;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.amazonaws.regions.Region;
import com.amazonaws.services.ec2.AmazonEC2Client;
import com.pearson.eidetic.aws.AwsAccount;
import com.pearson.eidetic.driver.threads.subthreads.SnapshotCleaner;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SnapshotCleaner_ESTest extends SnapshotCleaner_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer((-1973));
      Integer integer1 = new Integer((-1973));
      SnapshotCleaner snapshotCleaner0 = new SnapshotCleaner((AwsAccount) null, integer0, integer0, "", integer0, integer1);
      assertFalse(snapshotCleaner0.isFinished());
  }

  @Test
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(0);
      Integer integer1 = new Integer(0);
      SnapshotCleaner snapshotCleaner0 = new SnapshotCleaner((AwsAccount) null, integer0, integer0, "'gQ", integer1, integer0);
      assertFalse(snapshotCleaner0.isFinished());
  }

  @Test
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(152);
      SnapshotCleaner snapshotCleaner0 = new SnapshotCleaner((AwsAccount) null, integer0, (Integer) null, "XH34e|J[uQ|}U(", integer0, integer0);
      // Undeclared exception!
      try { 
        snapshotCleaner0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.pearson.eidetic.driver.threads.subthreads.SnapshotCleaner", e);
      }
  }

  @Test
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(1341);
      SnapshotCleaner snapshotCleaner0 = new SnapshotCleaner((AwsAccount) null, integer0, integer0, "DeleteOnTermination: ", integer0, integer0);
      // Undeclared exception!
      try { 
        snapshotCleaner0.connect((Region) null, "BJ;t1|]jpdh^M+Vd", "BJ;t1|]jpdh^M+Vd");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.pearson.eidetic.driver.threads.subthreads.SnapshotCleaner", e);
      }
  }

  @Test
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer((-1973));
      SnapshotCleaner snapshotCleaner0 = new SnapshotCleaner((AwsAccount) null, integer0, integer0, "", integer0, integer0);
      Boolean boolean0 = snapshotCleaner0.allSnapshotsClean((AmazonEC2Client) null);
      assertFalse(boolean0);
      assertFalse(snapshotCleaner0.isFinished());
  }

  @Test
  public void test5()  throws Throwable  {
      Integer integer0 = new Integer((-1973));
      SnapshotCleaner snapshotCleaner0 = new SnapshotCleaner((AwsAccount) null, integer0, integer0, "", integer0, integer0);
      Boolean boolean0 = snapshotCleaner0.eideticClean((AmazonEC2Client) null);
      assertFalse(snapshotCleaner0.isFinished());
      assertFalse(boolean0);
  }

  @Test
  public void test6()  throws Throwable  {
      Integer integer0 = new Integer((-1973));
      SnapshotCleaner snapshotCleaner0 = new SnapshotCleaner((AwsAccount) null, integer0, integer0, "", integer0, integer0);
      boolean boolean0 = snapshotCleaner0.isFinished();
      assertFalse(boolean0);
  }
}
