/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 28 16:57:13 GMT 2017
 */

package com.pearson.eidetic.driver.threads.subthreads;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SnapshotVolumeSyncValidator_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.pearson.eidetic.driver.threads.subthreads.SnapshotVolumeSyncValidator"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("os.name", "Mac OS X"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/Users/testuser"); 
    java.lang.System.setProperty("java.home", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre"); 
    java.lang.System.setProperty("user.dir", "/Users/testuser/Documents/NetBeansProjects/eidetic"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
    java.lang.System.setProperty("awt.toolkit", "sun.lwawt.macosx.LWCToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
    java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.CGraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.lwawt.macosx.CPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/EvoSuite_pathingJar5094989004039643449.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
    java.lang.System.setProperty("java.endorsed.dirs", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/Users/testuser/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_25-b17"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_25"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.version", "25.25-b02"); 
    java.lang.System.setProperty("os.arch", "x86_64"); 
    java.lang.System.setProperty("os.version", "10.10.5"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "testuser"); 
    java.lang.System.setProperty("user.timezone", "America/Chicago"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SnapshotVolumeSyncValidator_ESTest_scaffolding.class.getClassLoader() ,
      "com.amazonaws.services.ec2.model.MoveAddressToVpcRequest",
      "com.amazonaws.AmazonWebServiceClient",
      "com.amazonaws.services.ec2.model.AttachVolumeRequest",
      "com.amazonaws.services.ec2.model.ReleaseAddressRequest",
      "com.amazonaws.RequestClientOptions",
      "com.amazonaws.metrics.RequestMetricCollector",
      "com.amazonaws.event.ProgressListener$1",
      "com.amazonaws.services.ec2.model.StopInstancesRequest",
      "com.amazonaws.services.ec2.model.AssociateRouteTableRequest",
      "com.amazonaws.services.ec2.model.UnassignPrivateIpAddressesRequest",
      "com.amazonaws.services.ec2.model.DescribeInstancesRequest",
      "com.amazonaws.services.ec2.model.DescribePrefixListsRequest",
      "com.amazonaws.auth.AWSCredentials",
      "com.amazonaws.services.ec2.model.GetConsoleOutputRequest",
      "com.amazonaws.services.ec2.model.DescribeReservedInstancesRequest",
      "com.amazonaws.services.ec2.model.AssociateDhcpOptionsRequest",
      "com.amazonaws.metrics.RequestMetricCollector$1",
      "com.amazonaws.services.ec2.model.DescribeSpotFleetInstancesRequest",
      "com.amazonaws.services.ec2.model.ReplaceNetworkAclAssociationRequest",
      "com.amazonaws.services.ec2.model.DescribeConversionTasksRequest",
      "com.amazonaws.services.ec2.model.DescribeFlowLogsRequest",
      "com.amazonaws.services.ec2.model.DescribeMovingAddressesRequest",
      "com.amazonaws.services.ec2.model.DisableVpcClassicLinkRequest",
      "com.amazonaws.services.ec2.model.DescribeRouteTablesRequest",
      "com.amazonaws.services.ec2.model.DetachNetworkInterfaceRequest",
      "com.amazonaws.services.ec2.model.Tag",
      "com.amazonaws.services.ec2.model.RevokeSecurityGroupEgressRequest",
      "com.amazonaws.AmazonClientException",
      "com.pearson.eidetic.utilities.Threads",
      "com.amazonaws.services.ec2.model.RequestSpotFleetRequest",
      "com.amazonaws.services.ec2.model.DescribeKeyPairsRequest",
      "com.amazonaws.services.ec2.model.CancelSpotInstanceRequestsRequest",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "com.amazonaws.transform.Unmarshaller",
      "com.amazonaws.services.ec2.model.DescribeVolumesRequest",
      "com.amazonaws.services.ec2.model.DescribeVolumeStatusRequest",
      "com.amazonaws.services.ec2.model.CreateSpotDatafeedSubscriptionRequest",
      "com.amazonaws.services.ec2.model.CreateVpcRequest",
      "com.amazonaws.services.ec2.model.CreateNetworkAclRequest",
      "com.amazonaws.services.ec2.model.EnableVpcClassicLinkRequest",
      "com.amazonaws.services.ec2.model.DeleteDhcpOptionsRequest",
      "com.amazonaws.services.ec2.AmazonEC2Client",
      "com.amazonaws.services.ec2.model.PurchaseReservedInstancesOfferingRequest",
      "com.amazonaws.services.ec2.model.CreateFlowLogsRequest",
      "com.amazonaws.services.ec2.model.CreateRouteTableRequest",
      "com.amazonaws.services.ec2.model.ResetInstanceAttributeRequest",
      "com.amazonaws.services.ec2.model.AttachClassicLinkVpcRequest",
      "com.amazonaws.services.ec2.model.EnableVgwRoutePropagationRequest",
      "com.amazonaws.services.ec2.model.ImportKeyPairRequest",
      "com.amazonaws.log.CommonsLogFactory",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.amazonaws.services.ec2.model.DescribeInternetGatewaysRequest",
      "com.amazonaws.services.ec2.model.CreateRouteRequest",
      "com.amazonaws.services.ec2.model.ModifyVpcEndpointRequest",
      "com.amazonaws.services.ec2.model.ResetImageAttributeRequest",
      "com.amazonaws.services.ec2.model.DescribeVpcsRequest",
      "com.amazonaws.services.ec2.model.DescribeInstanceAttributeRequest",
      "com.amazonaws.services.ec2.model.DeregisterImageRequest",
      "com.amazonaws.metrics.MetricType",
      "com.amazonaws.services.ec2.model.CreateTagsRequest",
      "com.amazonaws.services.ec2.model.DescribeNetworkAclsRequest",
      "com.amazonaws.services.ec2.model.ReplaceNetworkAclEntryRequest",
      "com.amazonaws.services.ec2.model.RegisterImageRequest",
      "com.amazonaws.services.ec2.model.DeleteSubnetRequest",
      "com.amazonaws.services.ec2.model.DescribeRegionsRequest",
      "com.amazonaws.services.ec2.model.ModifyVolumeAttributeRequest",
      "com.amazonaws.services.ec2.model.DeleteVpnConnectionRequest",
      "com.amazonaws.services.ec2.model.Snapshot",
      "com.amazonaws.services.ec2.model.DeleteCustomerGatewayRequest",
      "com.amazonaws.services.ec2.model.ReplaceRouteRequest",
      "com.amazonaws.services.ec2.model.DescribeSnapshotsRequest",
      "com.amazonaws.services.ec2.model.DeleteRouteTableRequest",
      "org.json.simple.JSONStreamAware",
      "com.amazonaws.services.ec2.model.DeleteInternetGatewayRequest",
      "org.json.simple.JSONAware",
      "com.amazonaws.services.ec2.model.DescribeReservedInstancesListingsRequest",
      "com.amazonaws.services.ec2.model.DeleteFlowLogsRequest",
      "com.amazonaws.services.ec2.model.ReplaceRouteTableAssociationRequest",
      "com.amazonaws.services.ec2.model.ImportVolumeRequest",
      "com.amazonaws.services.ec2.model.RejectVpcPeeringConnectionRequest",
      "com.amazonaws.services.ec2.model.CreateVpcPeeringConnectionRequest",
      "com.amazonaws.services.ec2.model.DeleteKeyPairRequest",
      "com.amazonaws.services.ec2.model.DeleteVpnConnectionRouteRequest",
      "com.amazonaws.services.ec2.model.StartInstancesRequest",
      "com.amazonaws.services.ec2.model.CreatePlacementGroupRequest",
      "com.amazonaws.services.ec2.model.DetachClassicLinkVpcRequest",
      "com.amazonaws.services.ec2.model.ResetSnapshotAttributeRequest",
      "com.amazonaws.services.ec2.model.CreateVpnGatewayRequest",
      "com.amazonaws.services.ec2.model.DryRunSupportedRequest",
      "com.amazonaws.log.InternalLogFactory",
      "com.amazonaws.services.ec2.model.DescribeVpcEndpointServicesRequest",
      "com.amazonaws.services.ec2.model.DetachVpnGatewayRequest",
      "com.amazonaws.services.ec2.model.RunInstancesRequest",
      "com.amazonaws.services.ec2.model.ResetNetworkInterfaceAttributeRequest",
      "com.amazonaws.services.ec2.model.DeleteSecurityGroupRequest",
      "com.amazonaws.services.ec2.model.DescribeVpcClassicLinkRequest",
      "com.amazonaws.services.ec2.model.ModifySubnetAttributeRequest",
      "com.amazonaws.services.ec2.model.AssociateAddressRequest",
      "com.amazonaws.services.ec2.model.DescribeVpnGatewaysRequest",
      "com.amazonaws.services.ec2.model.DeleteVolumeRequest",
      "com.amazonaws.RequestClientOptions$Marker",
      "com.amazonaws.services.ec2.model.AcceptVpcPeeringConnectionRequest",
      "com.amazonaws.services.ec2.model.DeleteVpcEndpointsRequest",
      "com.amazonaws.services.ec2.model.CreateVpcEndpointRequest",
      "com.amazonaws.services.ec2.model.CopySnapshotRequest",
      "com.amazonaws.ReadLimitInfo",
      "com.amazonaws.services.ec2.model.DetachVolumeRequest",
      "com.amazonaws.services.ec2.model.ModifyReservedInstancesRequest",
      "com.amazonaws.services.ec2.model.AssignPrivateIpAddressesRequest",
      "com.amazonaws.services.ec2.model.DescribeSubnetsRequest",
      "com.amazonaws.services.ec2.model.EnableVolumeIORequest",
      "com.amazonaws.services.ec2.model.DeleteVpnGatewayRequest",
      "com.amazonaws.services.ec2.model.AttachInternetGatewayRequest",
      "com.amazonaws.services.ec2.model.AllocateAddressRequest",
      "com.amazonaws.services.ec2.model.DescribeDhcpOptionsRequest",
      "com.amazonaws.services.ec2.model.DescribeNetworkInterfaceAttributeRequest",
      "com.amazonaws.services.ec2.model.CreateDhcpOptionsRequest",
      "com.amazonaws.event.ProgressListener",
      "com.amazonaws.services.ec2.model.ModifyImageAttributeRequest",
      "com.amazonaws.services.ec2.model.ImportSnapshotRequest",
      "com.amazonaws.services.ec2.model.ModifySnapshotAttributeRequest",
      "com.amazonaws.services.ec2.model.CreateNetworkAclEntryRequest",
      "com.amazonaws.services.ec2.model.DeleteVpcRequest",
      "com.amazonaws.services.ec2.model.CancelBundleTaskRequest",
      "com.amazonaws.AmazonServiceException",
      "com.amazonaws.services.ec2.model.RevokeSecurityGroupIngressRequest",
      "com.amazonaws.services.ec2.model.RestoreAddressToClassicRequest",
      "com.amazonaws.services.ec2.model.DeleteNetworkInterfaceRequest",
      "com.amazonaws.services.ec2.model.GetPasswordDataRequest",
      "com.amazonaws.services.ec2.model.DescribePlacementGroupsRequest",
      "com.amazonaws.services.ec2.model.DeleteSpotDatafeedSubscriptionRequest",
      "com.amazonaws.services.ec2.model.CopyImageRequest",
      "com.amazonaws.http.HttpResponseHandler",
      "com.amazonaws.services.ec2.model.DescribeTagsRequest",
      "com.amazonaws.services.ec2.model.DeleteSnapshotRequest",
      "com.amazonaws.services.ec2.model.UnmonitorInstancesRequest",
      "com.amazonaws.services.ec2.model.DescribeVpnConnectionsRequest",
      "com.amazonaws.services.ec2.model.DescribeVpcPeeringConnectionsRequest",
      "com.amazonaws.services.ec2.model.CreateSubnetRequest",
      "com.amazonaws.services.ec2.model.CancelExportTaskRequest",
      "com.amazonaws.services.ec2.model.DescribeVolumeAttributeRequest",
      "com.amazonaws.services.ec2.model.AuthorizeSecurityGroupIngressRequest",
      "com.amazonaws.SignableRequest",
      "com.amazonaws.services.ec2.model.CreateInstanceExportTaskRequest",
      "com.pearson.eidetic.driver.threads.subthreads.SnapshotVolumeSyncValidator",
      "com.amazonaws.services.ec2.model.CancelImportTaskRequest",
      "com.amazonaws.services.ec2.model.DescribeNetworkInterfacesRequest",
      "com.amazonaws.services.ec2.model.DeleteVpcPeeringConnectionRequest",
      "com.amazonaws.services.ec2.model.RequestSpotInstancesRequest",
      "com.amazonaws.services.ec2.model.Volume",
      "com.amazonaws.auth.AWSCredentialsProvider",
      "com.amazonaws.services.ec2.model.DescribeSecurityGroupsRequest",
      "com.amazonaws.services.ec2.model.BundleInstanceRequest",
      "com.amazonaws.services.ec2.model.CreateCustomerGatewayRequest",
      "com.amazonaws.Protocol",
      "com.amazonaws.services.ec2.model.DescribeImageAttributeRequest",
      "com.amazonaws.services.ec2.model.DescribeReservedInstancesModificationsRequest",
      "com.amazonaws.services.ec2.model.DeleteTagsRequest",
      "com.amazonaws.services.ec2.model.ImportImageRequest",
      "com.amazonaws.services.ec2.model.ReportInstanceStatusRequest",
      "com.amazonaws.services.ec2.model.DetachInternetGatewayRequest",
      "com.amazonaws.services.ec2.model.TerminateInstancesRequest",
      "com.amazonaws.services.ec2.model.DescribeAddressesRequest",
      "com.amazonaws.log.JulLogFactory",
      "com.amazonaws.services.ec2.model.CreateSecurityGroupRequest",
      "com.amazonaws.services.ec2.model.CreateSnapshotRequest",
      "com.amazonaws.services.ec2.model.DescribeSpotInstanceRequestsRequest",
      "com.amazonaws.services.ec2.model.DescribeClassicLinkInstancesRequest",
      "com.pearson.eidetic.driver.threads.EideticSubThread",
      "com.amazonaws.services.ec2.model.DescribeExportTasksRequest",
      "com.amazonaws.services.ec2.model.DescribeSpotFleetRequestHistoryRequest",
      "com.amazonaws.services.ec2.model.DescribeSpotDatafeedSubscriptionRequest",
      "com.amazonaws.services.ec2.model.DescribeInstanceStatusRequest",
      "com.amazonaws.services.ec2.model.DescribeImagesRequest",
      "com.amazonaws.services.ec2.model.CreateVolumeRequest",
      "com.amazonaws.services.ec2.model.ImportInstanceRequest",
      "com.amazonaws.services.ec2.model.DescribeVpcEndpointsRequest",
      "com.amazonaws.services.ec2.model.DescribeAvailabilityZonesRequest",
      "com.amazonaws.services.ec2.model.CreateKeyPairRequest",
      "org.joda.time.ReadableInstant",
      "com.amazonaws.services.ec2.model.ModifyVpcAttributeRequest",
      "org.json.simple.JSONObject",
      "com.amazonaws.services.ec2.model.DescribeReservedInstancesOfferingsRequest",
      "com.amazonaws.services.ec2.model.DescribeVpcAttributeRequest",
      "com.amazonaws.services.ec2.model.DescribeSpotPriceHistoryRequest",
      "com.amazonaws.services.ec2.model.AuthorizeSecurityGroupEgressRequest",
      "com.amazonaws.services.ec2.model.ConfirmProductInstanceRequest",
      "com.amazonaws.services.ec2.model.RebootInstancesRequest",
      "com.amazonaws.Request",
      "com.amazonaws.services.ec2.model.DeletePlacementGroupRequest",
      "com.amazonaws.services.ec2.model.CreateNetworkInterfaceRequest",
      "com.amazonaws.services.ec2.model.CreateInternetGatewayRequest",
      "com.amazonaws.services.ec2.model.CreateImageRequest",
      "com.amazonaws.services.ec2.model.DescribeAccountAttributesRequest",
      "com.amazonaws.services.ec2.model.CancelConversionTaskRequest",
      "com.amazonaws.services.ec2.model.DeleteNetworkAclRequest",
      "com.amazonaws.services.ec2.model.AttachNetworkInterfaceRequest",
      "com.amazonaws.services.ec2.model.MonitorInstancesRequest",
      "com.amazonaws.services.ec2.model.DisassociateAddressRequest",
      "com.amazonaws.services.ec2.model.DescribeSnapshotAttributeRequest",
      "com.amazonaws.services.ec2.AmazonEC2",
      "com.amazonaws.services.ec2.model.AttachVpnGatewayRequest",
      "com.amazonaws.services.ec2.model.DescribeImportImageTasksRequest",
      "com.amazonaws.services.ec2.model.DescribeSpotFleetRequestsRequest",
      "com.amazonaws.services.ec2.model.Instance",
      "com.amazonaws.services.ec2.model.CancelReservedInstancesListingRequest",
      "com.amazonaws.AmazonWebServiceRequest$1",
      "com.amazonaws.AmazonWebServiceRequest",
      "com.amazonaws.services.ec2.model.CreateVpnConnectionRequest",
      "com.amazonaws.services.ec2.model.DescribeCustomerGatewaysRequest",
      "com.amazonaws.services.ec2.model.CancelSpotFleetRequestsRequest",
      "com.amazonaws.services.ec2.model.DescribeBundleTasksRequest",
      "com.amazonaws.services.ec2.model.DeleteNetworkAclEntryRequest",
      "com.amazonaws.services.ec2.model.CreateVpnConnectionRouteRequest",
      "com.amazonaws.services.ec2.model.DeleteRouteRequest",
      "com.amazonaws.services.ec2.model.ModifyNetworkInterfaceAttributeRequest",
      "com.amazonaws.services.ec2.model.DisassociateRouteTableRequest",
      "com.amazonaws.services.ec2.model.CreateReservedInstancesListingRequest",
      "com.amazonaws.services.ec2.model.ModifyInstanceAttributeRequest",
      "com.amazonaws.regions.Region",
      "com.amazonaws.services.ec2.model.DisableVgwRoutePropagationRequest",
      "com.pearson.eidetic.driver.threads.EideticSubThreadMethods",
      "com.amazonaws.services.ec2.model.DescribeImportSnapshotTasksRequest",
      "com.amazonaws.log.InternalLogApi"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SnapshotVolumeSyncValidator_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.pearson.eidetic.driver.threads.EideticSubThreadMethods",
      "com.pearson.eidetic.driver.threads.subthreads.SnapshotVolumeSyncValidator",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "com.pearson.eidetic.utilities.Threads",
      "com.amazonaws.Protocol",
      "com.amazonaws.event.ProgressListener",
      "com.amazonaws.RequestClientOptions",
      "com.amazonaws.RequestClientOptions$Marker",
      "com.amazonaws.AmazonWebServiceRequest",
      "com.amazonaws.services.ec2.model.CreateTagsRequest"
    );
  }
}
