/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 28 17:02:41 GMT 2017
 */

package com.pearson.eidetic.driver.threads.subthreads;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SnapshotVolumeSync_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.pearson.eidetic.driver.threads.subthreads.SnapshotVolumeSync"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("os.name", "Mac OS X"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/Users/testuser"); 
    java.lang.System.setProperty("java.home", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre"); 
    java.lang.System.setProperty("user.dir", "/Users/testuser/Documents/NetBeansProjects/eidetic"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
    java.lang.System.setProperty("awt.toolkit", "sun.lwawt.macosx.LWCToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
    java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.CGraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.lwawt.macosx.CPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/var/folders/cs/d6h1sj7j2g9_zhmr2syzkrysl5mt07/T/EvoSuite_pathingJar1057386279355105464.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
    java.lang.System.setProperty("java.endorsed.dirs", "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/Users/testuser/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_25-b17"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_25"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.version", "25.25-b02"); 
    java.lang.System.setProperty("os.arch", "x86_64"); 
    java.lang.System.setProperty("os.version", "10.10.5"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "testuser"); 
    java.lang.System.setProperty("user.timezone", "America/Chicago"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SnapshotVolumeSync_ESTest_scaffolding.class.getClassLoader() ,
      "com.fasterxml.jackson.databind.introspect.ClassIntrospector",
      "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl",
      "com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector",
      "com.amazonaws.AmazonWebServiceClient",
      "com.fasterxml.jackson.databind.AnnotationIntrospector",
      "com.fasterxml.jackson.core.Versioned",
      "com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver",
      "com.fasterxml.jackson.databind.node.TreeTraversingParser",
      "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
      "com.fasterxml.jackson.databind.node.NullNode",
      "com.pearson.eidetic.driver.threads.subthreads.SnapshotVolumeSync",
      "com.fasterxml.jackson.databind.cfg.MapperConfigBase",
      "com.fasterxml.jackson.databind.node.BaseJsonNode",
      "com.fasterxml.jackson.databind.JsonSerializable",
      "com.fasterxml.jackson.databind.JsonNode",
      "com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder",
      "com.amazonaws.auth.AWSCredentials",
      "org.joda.time.ReadableInstant",
      "com.amazonaws.regions.RegionUtils",
      "com.fasterxml.jackson.databind.type.TypeBase",
      "com.fasterxml.jackson.databind.deser.DeserializerFactory",
      "com.fasterxml.jackson.databind.node.ValueNode",
      "com.amazonaws.services.ec2.model.Snapshot",
      "org.json.simple.JSONObject",
      "com.amazonaws.services.ec2.model.VolumeState",
      "com.fasterxml.jackson.databind.deser.BasicDeserializerFactory",
      "com.amazonaws.services.ec2.model.Tag",
      "com.fasterxml.jackson.databind.ser.BasicSerializerFactory",
      "com.fasterxml.jackson.databind.cfg.MapperConfig",
      "com.fasterxml.jackson.databind.JsonMappingException",
      "com.fasterxml.jackson.databind.introspect.ClassIntrospector$MixInResolver",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "com.amazonaws.AmazonClientException",
      "com.amazonaws.internal.config.Builder",
      "com.fasterxml.jackson.databind.MappingJsonFactory",
      "com.fasterxml.jackson.databind.ser.SerializerFactory",
      "com.fasterxml.jackson.core.JsonGenerator",
      "org.json.simple.JSONStreamAware",
      "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext",
      "org.json.simple.JSONAware",
      "com.fasterxml.jackson.databind.jsontype.SubtypeResolver",
      "com.fasterxml.jackson.core.ObjectCodec",
      "com.fasterxml.jackson.databind.type.SimpleType",
      "com.amazonaws.util.VersionInfoUtils",
      "com.amazonaws.log.InternalLog",
      "com.fasterxml.jackson.databind.DatabindContext",
      "org.apache.commons.logging.impl.Log4JLogger",
      "com.amazonaws.util.json.Jackson",
      "com.fasterxml.jackson.core.type.ResolvedType",
      "com.amazonaws.regions.Regions",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "com.fasterxml.jackson.databind.DeserializationConfig",
      "com.fasterxml.jackson.core.io.SegmentedStringWriter",
      "com.fasterxml.jackson.databind.Module$SetupContext",
      "com.amazonaws.services.ec2.AmazonEC2",
      "com.amazonaws.services.ec2.model.Volume",
      "com.amazonaws.auth.AWSCredentialsProvider",
      "com.fasterxml.jackson.databind.SerializerProvider",
      "com.fasterxml.jackson.databind.JavaType",
      "com.amazonaws.services.ec2.model.Instance",
      "com.fasterxml.jackson.databind.deser.BeanDeserializerFactory",
      "com.amazonaws.internal.ListWithAutoConstructFlag",
      "com.amazonaws.services.ec2.AmazonEC2Client",
      "com.fasterxml.jackson.core.TreeNode",
      "com.fasterxml.jackson.core.TreeCodec",
      "com.fasterxml.jackson.databind.ser.BeanSerializerFactory",
      "com.amazonaws.auth.BasicAWSCredentials",
      "com.fasterxml.jackson.databind.DeserializationContext",
      "com.fasterxml.jackson.databind.introspect.VisibilityChecker",
      "com.fasterxml.jackson.core.JsonParser",
      "com.amazonaws.log.InternalLogFactory",
      "com.fasterxml.jackson.databind.ObjectMapper",
      "com.fasterxml.jackson.core.JsonProcessingException",
      "com.amazonaws.regions.RegionMetadataParser",
      "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl",
      "com.amazonaws.log.JulLogFactory",
      "com.fasterxml.jackson.core.JsonFactory",
      "com.fasterxml.jackson.databind.introspect.BasicClassIntrospector",
      "com.amazonaws.ClientConfiguration",
      "com.amazonaws.regions.RegionMetadata",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.fasterxml.jackson.core.base.ParserMinimalBase",
      "com.amazonaws.internal.config.InternalConfig$Factory",
      "com.amazonaws.internal.config.InternalConfig",
      "com.fasterxml.jackson.core.util.ByteArrayBuilder",
      "com.amazonaws.util.ClassLoaderHelper",
      "com.fasterxml.jackson.core.PrettyPrinter",
      "com.fasterxml.jackson.databind.util.StdDateFormat",
      "com.amazonaws.regions.Region",
      "com.amazonaws.services.ec2.model.VolumeAttachment",
      "com.amazonaws.services.ec2.model.VolumeType",
      "com.fasterxml.jackson.databind.util.TokenBuffer",
      "com.pearson.eidetic.driver.threads.EideticSubThreadMethods",
      "com.pearson.eidetic.driver.threads.EideticSubThread",
      "com.amazonaws.log.InternalLogApi"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SnapshotVolumeSync_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.pearson.eidetic.driver.threads.EideticSubThreadMethods",
      "com.pearson.eidetic.driver.threads.subthreads.SnapshotVolumeSync",
      "com.pearson.eidetic.utilities.StackTrace",
      "com.amazonaws.Protocol",
      "com.pearson.eidetic.globals.ApplicationConfiguration",
      "com.amazonaws.regions.Region",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "com.amazonaws.regions.RegionUtils",
      "com.amazonaws.regions.RegionMetadataParser",
      "com.amazonaws.services.ec2.model.Volume",
      "com.amazonaws.log.InternalLogFactory",
      "com.amazonaws.AmazonWebServiceClient",
      "com.amazonaws.util.VersionInfoUtils",
      "com.amazonaws.internal.config.InternalConfig",
      "com.amazonaws.util.ClassLoaderHelper",
      "com.amazonaws.util.json.Jackson",
      "com.amazonaws.internal.config.InternalConfig$Factory",
      "com.amazonaws.ClientConfiguration",
      "com.amazonaws.internal.ListWithAutoConstructFlag",
      "org.json.simple.JSONObject",
      "com.amazonaws.http.HttpRequestFactory",
      "com.amazonaws.http.AmazonHttpClient",
      "org.apache.http.params.BasicHttpParams",
      "com.amazonaws.auth.AWSCredentialsProviderChain",
      "com.amazonaws.auth.profile.ProfileCredentialsProvider",
      "com.amazonaws.util.StringUtils",
      "com.amazonaws.auth.InstanceProfileCredentialsProvider",
      "com.amazonaws.services.ec2.model.VolumeAttachment",
      "com.amazonaws.services.ec2.model.Tag",
      "com.amazonaws.services.ec2.model.Snapshot",
      "org.joda.time.base.BaseDateTime",
      "org.joda.time.DateTime",
      "org.joda.time.DateTimeUtils",
      "org.joda.time.chrono.BaseChronology",
      "org.joda.time.chrono.AssembledChronology",
      "org.joda.time.field.MillisDurationField",
      "org.joda.time.field.BaseDurationField",
      "org.joda.time.field.PreciseDurationField",
      "org.joda.time.DurationFieldType$StandardDurationFieldType",
      "org.joda.time.DurationFieldType",
      "org.joda.time.field.PreciseDurationDateTimeField",
      "org.joda.time.field.PreciseDateTimeField",
      "org.joda.time.DateTimeFieldType$StandardDateTimeFieldType",
      "org.joda.time.DateTimeFieldType",
      "org.joda.time.field.DecoratedDateTimeField",
      "org.joda.time.field.ZeroIsMaxDateTimeField",
      "org.joda.time.chrono.BasicChronology$HalfdayField",
      "org.joda.time.chrono.BasicChronology",
      "org.joda.time.chrono.BasicGJChronology",
      "org.joda.time.UTCDateTimeZone",
      "org.joda.time.DateTimeZone",
      "org.joda.time.field.ImpreciseDateTimeField",
      "org.joda.time.chrono.BasicYearDateTimeField",
      "org.joda.time.field.ImpreciseDateTimeField$LinkedDurationField",
      "org.joda.time.chrono.GJYearOfEraDateTimeField",
      "org.joda.time.field.OffsetDateTimeField",
      "org.joda.time.field.DividedDateTimeField",
      "org.joda.time.field.DecoratedDurationField",
      "org.joda.time.field.ScaledDurationField",
      "org.joda.time.field.RemainderDateTimeField",
      "org.joda.time.chrono.GJEraDateTimeField",
      "org.joda.time.chrono.GJDayOfWeekDateTimeField",
      "org.joda.time.chrono.BasicDayOfMonthDateTimeField",
      "org.joda.time.chrono.BasicDayOfYearDateTimeField",
      "org.joda.time.chrono.BasicMonthOfYearDateTimeField",
      "org.joda.time.chrono.GJMonthOfYearDateTimeField",
      "org.joda.time.chrono.BasicWeekyearDateTimeField",
      "org.joda.time.chrono.BasicWeekOfWeekyearDateTimeField",
      "org.joda.time.field.UnsupportedDurationField",
      "org.joda.time.chrono.GregorianChronology",
      "org.joda.time.chrono.ISOYearOfEraDateTimeField",
      "org.joda.time.chrono.ISOChronology",
      "org.joda.time.tz.DateTimeZoneBuilder$PrecalculatedZone",
      "org.joda.time.tz.DateTimeZoneBuilder$DSTZone",
      "org.joda.time.tz.CachedDateTimeZone",
      "org.joda.time.chrono.ZonedChronology",
      "org.joda.time.chrono.ZonedChronology$ZonedDurationField",
      "org.joda.time.chrono.ZonedChronology$ZonedDateTimeField",
      "org.joda.time.convert.ConverterManager",
      "org.joda.time.convert.ReadableInstantConverter",
      "org.joda.time.convert.StringConverter",
      "org.joda.time.convert.CalendarConverter",
      "org.joda.time.convert.DateConverter",
      "org.joda.time.convert.LongConverter",
      "org.joda.time.convert.NullConverter",
      "org.joda.time.convert.ReadablePartialConverter",
      "org.joda.time.convert.ReadableDurationConverter",
      "org.joda.time.convert.ReadableIntervalConverter",
      "org.joda.time.convert.ReadablePeriodConverter",
      "org.joda.time.base.BaseSingleFieldPeriod",
      "org.joda.time.format.ISOPeriodFormat",
      "org.joda.time.format.PeriodFormatterBuilder",
      "org.joda.time.format.PeriodFormatterBuilder$Literal",
      "org.joda.time.PeriodType",
      "org.joda.time.Minutes",
      "com.amazonaws.event.ProgressListener",
      "com.amazonaws.RequestClientOptions",
      "com.amazonaws.RequestClientOptions$Marker",
      "com.amazonaws.AmazonWebServiceRequest",
      "com.amazonaws.services.ec2.model.CreateSnapshotRequest",
      "com.pearson.eidetic.aws.EC2ClientMethods",
      "com.pearson.eidetic.globals.GlobalVariables",
      "com.pearson.eidetic.utilities.Threads",
      "com.amazonaws.services.ec2.model.CreateTagsRequest"
    );
  }
}
