/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 04 21:13:16 GMT 2016
 */

package com.pearson.eidetic.driver.threads.subthreads;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.amazonaws.regions.Region;
import com.pearson.eidetic.aws.AwsAccount;
import com.pearson.eidetic.driver.threads.subthreads.TagChecker;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class TagChecker_ESTest extends TagChecker_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Integer integer1 = new Integer(1);
      TagChecker tagChecker0 = new TagChecker((AwsAccount) null, "CrossAz", (String) null, integer0, integer1);
  }

  @Test
  public void test1()  throws Throwable  {
      TagChecker tagChecker0 = new TagChecker((AwsAccount) null, ",^*", ",^*", (Integer) null, (Integer) null);
      // Undeclared exception!
      try { 
        tagChecker0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.pearson.eidetic.driver.threads.subthreads.TagChecker", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      TagChecker tagChecker0 = new TagChecker((AwsAccount) null, "\",Event\"Error\", Error=\"volume id does not exist\", stacktrace=\"", "\",Event\"Error\", Error=\"volume id does not exist\", stacktrace=\"", (Integer) null, (Integer) null);
      // Undeclared exception!
      try { 
        tagChecker0.connect((Region) null, "\",Event\"Error\", Error=\"volume id does not exist\", stacktrace=\"", "\",Event\"Error\", Error=\"volume id does not exist\", stacktrace=\"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.pearson.eidetic.driver.threads.subthreads.TagChecker", e);
      }
  }

  @Test
  public void test3()  throws Throwable  {
      TagChecker tagChecker0 = new TagChecker((AwsAccount) null, "\",Event=\"Error\", Error=\"error in TagChecker workflow\", stacktrace=\"", "\",Event=\"Error\", Error=\"error in TagChecker workflow\", stacktrace=\"", (Integer) null, (Integer) null);
      // Undeclared exception!
      try { 
        tagChecker0.isFinished();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("com.pearson.eidetic.driver.threads.subthreads.TagChecker", e);
      }
  }
}
