/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 28 16:40:47 GMT 2017
 */

package com.pearson.eidetic.network.http;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pearson.eidetic.network.http.JettySync;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class JettySync_ESTest extends JettySync_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          JettySync jettySync0 = new JettySync((-1033), (-1033));
          jettySync0.startServer();
          jettySync0.startServer();
          jettySync0.startServer();
          JettySync jettySync1 = new JettySync(8, 1425);
          jettySync1.startServer();
          jettySync1.startServer();
          jettySync0.startServer();
          jettySync1.stopServer();
          jettySync1.stopServer();
          jettySync1.stopServer();
          jettySync0.startServer();
          jettySync1.stopServer();
          jettySync0.stopServer();
          jettySync1.startServer();
          jettySync0.stopServer();
          jettySync1.stopServer();
          jettySync1.startServer();
          jettySync0.startServer();
          jettySync1.stopServer();
          JettySync jettySync2 = new JettySync((-1658), (-1033));
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }
}
